<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="home.css" />
    <style>
    body{
      background:url("images/bus4.jpg");
      background-repeat:no-repeat;
      background-size: cover;
    }
  </style>
    <link
      rel="stylesheet"
      href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css"
    />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js">
      <title>Bus</title>
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js">
    </script>
    <script>

    function destination(val){
      var error = document.getElementById("error");
      var startlocation = document.getElementById("startlocation").value;
      var destination = document.getElementById("destination").value;
      if(startlocation==destination){
        error.textContent = "Please enter different destination"
        error.style.color = "red"
      }else {
            error.textContent = ""
        }
    }
    </script>
    <script type="text/javascript">
      $(function () {
        var today = new Date();
        var month = ("0" + (today.getMonth() + 1)).slice(-2);
        var day = ("0" + today.getDate()).slice(-2);
        var year = today.getFullYear();
        var date = year + "-" + month + "-" + day;
        $("[id*=date]").attr("min", date);
      });
    </script>
    <script>
      function calculateAmount(val) {
        var tot_price = val * 5;
        var divobj = document.getElementById("tot_amount");
        divobj.value = tot_price;
        var divobj1 = document.getElementById("TXN_AMOUNT");
        divobj1.value = tot_price;
        var startlocation = document.getElementById("startlocation").value;
        var destination = document.getElementById("destination").value;
        var date = document.getElementById("date").value;
        var time = document.getElementById("time").value;
        var seat = document.getElementById("seat").value;
        var ORDER_ID = document.getElementById("ORDER_ID").value;
        document.cookie = "startlocation" + "=" + startlocation;
        document.cookie = "destination" + "=" + destination;
        document.cookie = "date" + "=" + date;
        document.cookie = "time" + "=" + time;
        document.cookie = "seat" + "=" + seat;
        document.cookie = "price" + "=" + tot_price;
        document.cookie = "oderid" + "=" + ORDER_ID;
      }
    </script>
  </head>

  <body>
    <?php
        $custid=base64_encode('cust'.rand(1000,1000));
        $amount=base64_encode(4000);
        $orderid="ORDS" . rand(10000,99999999);
        ?>
    <nav id="navbar">
      <div id="logo">Multi purpose <br />Ticket booking system</div>
      <div>
        <ul>
          <li class="item"><a href="h.php">Home</a></li>
          <li class="item"><a href="bus.php">Bus</a></li>
          <li class="item"><a href="train.php">Train</a></li>
          <li class="item"><a href="helpdesk.html">Help Desk</a></li>
          <li class="item">
            <a href="nearbyLocation.php">Bus Stop Locater</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="bus">
      <div class="bus1">
        <!-- <form action="paymentbus.php" method="post" > -->
        <h2>Book bus ticket</h2>
        <div class="form-group">
          <h3>Start Location</h3>
          <input
            type="text"
            class="form-control"
            name="startlocation"
            id="startlocation"
            require
          />
          <!-- <select class="form-control" id="startlocation" name="startlocation" required>
                        <option>Andheri</option>
                        <option>Vijay</option>
                    </select> -->
        </div>
        <div class="form-group">
          <h3>Destination</h3>
          <input
            type="text"
            class="form-control"
            name="destination"
            id="destination"
            onchange="destination(this.value)"
            require
          />
        </div>
        <span id="error"></span>
        <div class="form-group">
          <h3>Date</h3>
          <input
            class="form-control"
            id="date"
            type="date"
            name="date"
            required
          />
        </div>
        <div class="form-group">
          <h3>Time</h3>
          <input
            class="form-control"
            id="time"
            type="time"
            name="time"
            required
          />
        </div>
        <div class="form-group">
          <h3>Seat</h3>
          <input
            class="form-control"
            id="seat"
            type="number"
            name="seat"
            onchange="calculateAmount(this.value) "
            required
          /><br />
        </div>
        <div class="form-group">
          <h3>Price</h3>
          <input
            class="form-control"
            name="price"
            id="tot_amount"
            type="text"
            readonly
          />
          <!-- </form> -->
          <div class="form-group">
            
            <form method="post" action="pgRedirect.php" target="_blank">
              <input value="Payment" type="submit" class="btn" />
              <input
                type="hidden"
                id="ORDER_ID"
                tabindex="1"
                maxlength="20"
                size="20"
                name="ORDER_ID"
                autocomplete="off"
                value="<?php echo $orderid;  ?>"
              />
              <input
                type="hidden"
                id="CUST_ID"
                tabindex="2"
                maxlength="12"
                size="12"
                name="CUST_ID"
                autocomplete="off"
                value="siddhi"
              />
              <input
                type="hidden"
                id="INDUSTRY_TYPE_ID"
                tabindex="4"
                maxlength="12"
                size="12"
                name="INDUSTRY_TYPE_ID"
                autocomplete="off"
                value="Retail"
              />
              <input
                type="hidden"
                id="CHANNEL_ID"
                tabindex="4"
                maxlength="12"
                size="12"
                name="CHANNEL_ID"
                autocomplete="off"
                value="WEB"
              />
              <input
                type="hidden"
                title="TXN_AMOUNT"
                tabindex="10"
                type="text"
                id="TXN_AMOUNT"
                name="TXN_AMOUNT"
                value="<?php echo $price;  ?>"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
    <script>
              $( function() {
              var availableTags = [
              "A.D.MODI INSTITUTE",
              "A.H.ANSARI CHOWK",
              "A.H.SCHOOL",
              "A.P.M.COMPLEX",
              "A.T.I.",
              "AAI TULJABHAVANI CHK",
              "AAKASH GANGA SOCIETY (DHARAVI)",
              "AAREY HOSPITAL-MUNICIPAL SCHOOL",
              "AAREY ROAD SUBWAY",
              "ABHINAV NAGAR",
              "ABHINAV SCHOOL",
              "ABHISHEK APARTMENTS",
              "ABHYUDAYA BANK",
              "ACHARYA ATRE CHOWK",
              "ACHARYA GARDEN-DIAMOND GARDEN",
              "ACHARYA MARATHE COLLEGE",
              "ACHARYA VIDYANIKETAN",
              "ACHRYA VINOBA BHAVE NAGAR",
              "ADARSH BALWADI",
              "ADARSH DAIRY",
              "ADARSH HIGH SCHOOL",
              "ADARSH NAGAR (GOREGAON)",
              "ADARSH NAGAR (MALAD)",
              "ADARSH NAGAR (OSH)",
              "ADARSH NAGAR (WORLI)",
              "ADARSH NAGAR NAKA (GOREGAON)",
              "ADARSH VIDYALAYA",
              "ADARSHA MARKET (NERUL)",
              "ADISHAKTI NAGAR(YOGI HILL)",
              "ADV.PALJIBHAI BORICHA CHOWK",
              "AFGHAN CHURCH",
              "AGAR BAZAR",
              "AGARKAR CHOWK",
              "AGARWADI",
              "AGARWAL MUNICIPAL HOSPITAL",
              "AGHADI NAGAR",
              "AGRA ROAD NAKA",
              "AGRAWAL GREEN VILLAGE",
              "AGRIPADA POLICE STATION",
              "AHILYABAI HOLKAR CHOWK",
              "AIR CONDITION MARKET",
              "AIR INDIA QUARTERS",
              "AIROLI BUS STATION",
              "AIROLI SEWERAGE PLANT - PREMDAN",
              "AJARA BANK",
              "AJIT GLASS FACTORY",
              "AKSA BEACH",
              "AKSA VILLAGE",
              "AKSHAYA (BANDRA)",
              "AKSHAYA (MIRA ROAD)",
              "AL BARKAT HIGH SCHOOL",
              "ALANKAR TALKIES",
              "ALBERT ROAD-TANAJI MALUSARE CHOWK",
              "ALEXANDRA CINEMA",
              "ALIKA NAGAR JUNCTION",
              "ALLAHABAD BANK",
              "AMAR BRASS & STEEL COMPANY",
              "AMAR MAHAL",
              "AMAR NAGAR",
              "AMAR TALKIES",
              "AMARNATH PATIL SPORTS COMPLEX - BAN GANGA",
              "AMBA WADI",
              "AMBAJI DHAM",
              "AMBASSADOR HOTEL",
              "AMBE WADI",
              "AMBEDKAR BHAVAN (VIDYA NAGARI)",
              "AMBIKA MILLS - KING GEORGE INFERNARY",
              "AMBIKA NAGAR",
              "AMBIKA NAGAR THANE",
              "AMBOLI NAKA",
              "AMBOLI VILLAGE",
              "AMCHI SCHOOL",
              "AMIRA APARTMENTS (MALVANI)",
              "AMRAPALI SOCIETY (MALVANI)",
              "AMRUT NAGAR",
              "AMRUT SHAKTI",
              "AMRUTA VIDYALAYA (JUINAGAR)",
              "AMULAKH HIGH SCHOOL",
              "ANAND HOSPITAL",
              "ANAND NAGAR (APPAPADA)",
              "ANAND NAGAR (DAHISAR)",
              "ANAND NAGAR (OSHIWARA)",
              "ANAND NAGAR GHODBUNDER",
              "ANAND NAGAR MARKET",
              "ANAND NAGAR POLICE CHOWKY",
              "ANAND NAGAR TOLL NAKA (THANE)",
              "ANANT BHOOMI COMPELX (KANDIVALI W)",
              "ANDHERI FIRE BRIGADE",
              "ANDHERI MARKET",
              "ANDHERI SPORTS COMPLEX",
              "ANDHERI STATION (W)",
              "ANGAN WADI",
              "ANIK DEPOT",
              "ANIRUDDHA BHAVAN (JUINAGAR)",
              "ANITA NAGAR",
              "ANITA VIHAR",
              "ANJANABAI MAGAR",
              "ANJEER WADI",
              "ANJUMAN COLLEGE",
              "ANKUR ESTATE AGENCY",
              "ANKUR HOSPITAL",
              "ANKUR PALACE",
              "ANNABHAU SATHE CHOWK (THANE)",
              "ANNABHAU SATHE NAGAR",
              "ANTOP HILL",
              "ANTOP HILL CHURCH",
              "ANTOP HILL EXTENSION",
              "ANTOP HILL POLICE STATION",
              "ANTOP HILL POST OFFICE",
              "ANTOP HILL SECTOR 7",
              "ANUSHAKTI NAGAR",
              "APARNA WELFARE SOCIETY",
              "APEEJAY SCHOOL",
              "APNA BAZAR (MIRA RD)",
              "APNA BAZAR (PAREL)",
              "APNA BAZAR (VASHI)",
              "APPAPADA",
              "ARIHANT INDUSTRIAL ESTATE",
              "AROGYA HOSPITAL - D MART",
              "ARUNODAYA NAGAR",
              "ARYA SAMAJ MANDIR",
              "ASALPHA VILLAGE",
              "ASHA & USHA ESTATES",
              "ASHIRVAD HOSPITAL",
              "ASHIRVAD SOCIETY",
              "ASHISH COMPLEX",
              "ASHISH NAGAR",
              "ASHMITA COMPLEX",
              "ASHOK HOSPITAL",
              "ASHOK KEDARE CHOWK",
              "ASHOK NAGAR",
              "ASHOK NAGAR - VILO'S SOCIETY",
              "ASHOK VAN",
              "ASHTAGANDHA SOCIETY (NERUL)",
              "ASIAN PAINTS",
              "ASMITA JYOTI",
              "ASMITA SUPER MARKET",
              "ATMARAM NAGAR (SRUSHTI)",
              "ATMARAM TOWER",
              "ATRIA SOCIETY (BRAHMAND)",
              "AUGUST KRANTI MAIDAN",
              "AVDHUT NAGAR",
              "AYYAPPA MANDIR",
              "AZAD FLOUR MILL",
              "AZAD NAGAR (ANDHERI)",
              "AZAD NAGAR (PARLE)",
              "AZAD NAGAR (WADALA)",
              "AZAD NAGAR MIRA ROAD",
              "AZIZ BAUG",
              "B.A.P.MARKET",
              "B.A.R.C.SCHOOL NO.6",
              "B.D.PATIL MARG - HPCL (CHEMBUR)",
              "B.H.E.L.COMPANY",
              "B.M.C.COMPOST PLANT",
              "B.M.C.GARDEN (GOREGAON W)",
              "B.M.C.OFFICE DAHISAR",
              "B.P.T.COLONY (COTTON GREEN)",
              "B.P.T.COLONY (MAZAGAON)",
              "B.P.T.COLONY (WADALA - E)",
              "B.P.T.HOSPITAL (WADALA -E)",
              "B.S.E.S. (S'CRUZ)",
              "B.S.E.S.(SWAMI SAMARTH NAGAR)",
              "B.S.E.S.SUB STATION (CHEMBUR)",
              "BABASAHEB WORLIKAR CHOWK",
              "BABHAI NAKA",
              "BABU GENU MARKET",
              "BABULNATH",
              "BACKBAY DEPOT",
              "BADHWAR PARK - MACHHIMAR NAGAR",
              "BAFIRA NAGAR",
              "BAHALE PADA",
              "BAHAR CINEMA",
              "BAIL BAZAR",
              "BAINGAN WADI",
              "BAJAJ BHAVAN",
              "BAL BHARATI - HITAVARDHAK HALL",
              "BALAJI NAGAR",
              "BALBHARATI VIDYALAYA (KHARGHAR)",
              "BALKANJI BARI SCHOOL",
              "BALKUM NAKA",
              "BALKUM PADA NO.1",
              "BALLARD PIER",
              "BAMAN PADA",
              "BAMANDAYA PADA",
              "BANDONGRI",
              "BANDRA BUS STATION (WEST)",
              "BANDRA COLONY BUS STATION",
              "BANDRA EAST BUS STATION",
              "BANDRA PHATAK (E)",
              "BANDRA POLICE STATION",
              "BANDRA RAILWAY TERMINUS",
              "BANDRA RECLAMATION BUS STATION",
              "BANDRA STATION (E)",
              "BANDRA STATION ROAD (W)",
              "BANDRA TALAO",
              "BANDRA TALKIES",
              "BANGUR HALL",
              "BANGUR NAGAR",
              "BANGUR NAGAR POLICE CHOWKEY",
              "BANK OF BARODA BKC",
              "BANK OF BARODA JOGESHWARI",
              "BANK OF BARODA MALAD",
              "BANK OF INDIA ANDHERI",
              "BANK OF INDIA BANDRA",
              "BANK OF INDIA BKC",
              "BANK OF MAHARASTHRA - ODEON CINEMA",
              "BANK OF MAHARASTHRA CHARKOP",
              "BANUBAI TANDEL MARKET",
              "BANWARI COMPOUND",
              "BARC GATE NO.6",
              "BARKAT ALI DARGAH",
              "BASANT PAR",
              "BARVE NAGAR - MUNICIPAL SCHOOL NO ",
              "BASANT TALKIE",
              "BAWLA MASJI",
              "BAYER HOUS",
              "BEAUTY GURU",
              "BEHRAM BAU",
              "BELA NIVA",
              "BELE VILLA HOSPITA",
              "BELPADA VILLAG",
              "BEST COLONY BHOIWAD",
              "BEST NAGA",
              "BEST OFFICER QUARTERS GORA",
              "BEST POWER HOUSE (KUSSARA)",
              "BEST QUARRIES (CHANDIVALI)",
              "BEST RECEIVING CENTRE (PRATIKSHA NAGAR)",
              "BEVERLY PAR",
              "BHABREKAR NAGAR EXTENSIO",
              "BHABREKAR NAGAR NO.",
              "BHABREKAR NAGAR NO.",
              "BHAGAT SINGH NAGA",
              "BHAGWATI HOSPITAL",
              "BHAKTI BHAVA",
              "BHAKTI PALACE (DAHISAR)",
              "BHAKTI PARK COMPLE",
              "BHAKTI PARK GAT",
              "BHAKTI VEDAN",
              "BHANDUP PEOPLES SCHOO",
              "BHANDUP POLICE STATIO",
              "BHANDUP PUMPING CENTR",
              "BHANDUP STATION (E)",
              "BHANDUP VILLAGE (E)",
              "BHANDUP STATION (W)",
              "BHANDUP VILLAGE (W)",
              "BHANDUP VILLAGE JUN",
              "BHARANI NAKA (ANTOP)",
              "BHARAT DIAMOND BORSE",
              "BHARAT NAGAR BANDRA",
              "BHARAT NAGAR BKC",
              "BHARAT NAGAR JUHU",
              "BHARAT PETROLEUM CHEMBUR",
              "BHARATI VIDYAPITH",
              "BHARATIYA AROGYA NIDHI HOSPITAL",
              "BHARATMATA CINEMA",
              "BHAT WADI",
              "BHATI VILLAGE",
              "BHATIA HOSPITAL",
              "BHAVISHYA NIDHI BHAVAN",
              "BHAVANS COLLEGE",
              "BHAYANDAR PADA",
              "BHAYANDAR PHATAK",
              "BHAYANDAR POLICE STATION",
              "BHAYANDAR RAILWAY STATION (WEST)",
              "BHAYANDER MARKET",
              "BHAYANDER PHATAK (POLICE CHOWKY)",
              "BHAYANDER STATION (E)",
              "BHOI WAD",
              "BHULESHWA",
              "BHUMI COMPLE",
              "BHUSA INDUSTRIAL ESTAT",
              "BHUTTA COLLEG",
              "BIMBISAR NAGA",
              "BIRLA COMPAN",
              "BIRLA KRIDA KENDR",
              "BISHOP SCHOOL (BHAYANDAR)",
              "BKC TELEPHONE EXCHANG",
              "BLDG.NO 46 (BANDRA)",
              "BLIND PRES",
              "BLOSSOM CO-OP HOUSING SOCIET",
              "BLOSSOM COMPAN",
              "BMC WARD OFFIC",
              "BOMBAY DYEIN",
              "BONKODE VILLAG",
              "BORIVALI JAIL (W)",
              "BORIVALI MARKE",
              "BORIVALI PHATAK (E)",
              "BORIVALI STATION (E)",
              "BORIVALI STATION ROAD (W)",
              "BOROSIL GLASS FACTORY",
              "BPCL SPORTS CLUB MAHUL",
              "BRAHMAND - AZAD NAGAR",
              "BRAHMAND PHASE -3",
              "BRAHMAND PHASE -5",
              "BRAHMAND PHASE -6",
              "BRAHMAND-AZAD NAGAR BUS STATION",
              "BRAMHALA TALAO - MANOR PADA",
              "BRAMHAND - AZAD NAGAR JUNCTION",
              "BREACH CANDY HOSPITAL",
              "BRIMCO",
              "BUDDHA NAGAR",
              "BUDDHA NAGAR JUNCTION",
              "BYCULLA POLICE STATION",
              "BYCULLA STATION (E)",
              "BYCULLA STATION (W)",
              "BYCULLA TELEPHONE EXCHANGE",
              "C & D SHED COTTON GREEN",
              "C CROSS ROAD JUNCTION",
              "C CROSS ROAD JUNCTION",
              "C.A.IN STITUTE BKC",
              "C.B.D.BELAPUR BUS STATION",
              "C.B.I.QRTS",
              "C.C.I",
              "C.C.I.COLONY",
              "C.G.S.COLONY (BHANDUP)",
              "C.G.S.DISPENSARY",
              "C.K.P.COLONY",
              "CADBURY JUNCTION",
              "CAFE PARADISE",
              "CALICO MILLS",
              "CANARA BANK BKC",
              "CANOSSA SCHOOL",
              "CANTEEN STORES DEPARTMENT",
              "CARDINAL GRACIOUS SCHOOL - TEACHERS COLONY",
              "CARNAC BUNDER",
              "CASTLE MILL (THANE)",
              "CATERING COLLEGE",
              "CAVES ROAD",
              "CEAT COMPANY",
              "CENTRAL DAIRY",
              "CENTRAL DAIRY TABELA",
              "CENTRAL LABOUR INSTITUTE",
              "CENTRAL RAILWAY GOODS SHED",
              "CENTRAL TALKIES",
              "CENTRAL WARE HOUSING CORPORATION",
              "CEREMONIAL HALL (YOGI HILLS)",
              "CHAINANI ELDER'S HOME'",
              "CHAITANYA HOSPITAL MIRA ROAD",
              "CHAKALA",
              "CHAKALA (SATAM WADI)",
              "CHAKALA CIGARETTE FACTORY",
              "CHAKALA MARKET",
              "CHANDAN CINEMA",
              "CHANDIVALI JUNCTION",
              "CHANDIVALI STUDIO - NAHAR ENTERPRISE",
              "CHANDIVALI VILLAGE",
              "CHAR NAL",
              "CHARATSINGH COLONY",
              "CHARKOP EKDANT SOCIETY",
              "CHARKOP NAKA",
              "CHARKOP POLICE STATION",
              "CHARKOP SECTOR-9 - AKSHARA VIDYALAYA",
              "CHARKOP VILLAGE",
              "CHARNI ROAD RAILWAY STATION",
              "CHEETA CAMP (TROMBAY)",
              "CHEMBUR COLONY",
              "CHEMBUR LEVEL CROSSING - SHELL BRIDGE",
              "CHEMBUR NAKA - SWAMI VIVEKANAND CHOWK",
              "CHEMBUR STATION ROAD NO 1",
              "CHH.SHIVAJI INT.AIRPORT(SAHAR)",
              "CHHEDA NAGAR",
              "CHHOTA KASHMIR POLICE STATION",
              "CHIKOO WADI - PADMA NAGAR",
              "CHILDRENS HOME",
              "CHINA BRIDGE",
              "CHINAI COLLEGE",
              "CHINCH BUNDER",
              "CHINCH PADA",
              "CHINCH WADI - GARTEN PADA NO.1",
              "CHINCHOLI BUNDER ROAD",
              "CHINCHOLI PHATAK - SARVODAYA SCHOOL",
              "CHINCHOLI TALAO (NERUL)",
              "CHIRA BAZAR",
              "CHIRAG NAGAR",
              "CHITRA CINEMA",
              "CHITRAGAN SOCIETY",
              "CHOGLE NAGAR",
              "CHOKSI HOSPITAL",
              "CHOTHA KASHMIR - OBSERVATORY POINT",
              "CHOWPATI BAND STAND",
              "CHRIST CHURCH SCHOOL",
              "CHUIM VILLAGE",
              "CHUNABHATTI",
              "CIBA COMPANY",
              "CINEMAX MIRA ROAD",
              "CITI BANK BKC",
              "CITIZEN BANK BORIVALI",
              "CITYLIGHT CINEMA",
              "COAL BUNDER",
              "COCA COLA COMPANY",
              "COLABA BUS STATION",
              "COLABA DEPOT",
              "COLABA POST OFFICE",
              "COM.GULABRAO GANACHARYA CHOWK",
              "COM.P.K.KURNE CHOWK",
              "COOPERAGE TELEPHONE EXCHANGE",
              "CORPORATION BANK DAHISAR",
              "COSMOS HIGH SCHOOL",
              "CRESCENZO",
              "CRISIL HOUSE (POWAI)",
              "CROMPTON GREAVES BHANDUP",
              "CRYSTAL HOSPITAL",
              "CUFFE PARADE POLICE STATION",
              "CUMBALA HILL POST OFFICE",
              "D MART SHOPPING CENTRE",
              "D'MONTE GARDEN",
              "D'SUZA NAGAR",
              "D.A.V.COLLEGE BHANDUP",
              "D.N.NAGAR - BARFIWALA VIDYALAYA",
              "DADAR CREMATORIUM - CHAITYABHUMI",
              "DADAR KABUTAR KHANA",
              "DADAR POLICE STATION",
              "DADAR POST OFFICE",
              "DADASAHEB PHALKE CHITRA NAGARI",
              "DADLANI PARK",
              "DADOJI KONDEV NAGAR (KHARDEV NAGAR)",
              "DAHANUKAR WADI",
              "DAHISAR BRIDGE",
              "DAHISAR BUS STATION",
              "DAHISAR CHECK NAKA (E)",
              "DAHISAR MARKET",
              "DAHISAR PHATAK (W)",
              "DAHISAR STATION (W)",
              "DAHISAR STATION ROAD (E)",
              "DAIRY RESEARCH INSTITUTE",
              "DAKC GATE NO.1",
              "DAKC GATE NO.2",
              "DAMAYANTI SOCIETY (THANE)",
              "DAMU NAGAR - MAYUR MARKET",
              "DAMU NAGAR BUS STATION",
              "DAMU NAGAR EXTENSION",
              "DANA BAZAR",
              "DANA BAZAR SECTOR 19",
              "DANDA PADA",
              "DARGAH VIKHROLI",
              "DARPAN CINEMA - SAI SERVICE",
              "DARU KHANA",
              "DARYA MAHAL",
              "DATTA MANDIR (DAHANUKAR WADI)",
              "DATTA MANDIR (INCOME TAX COLONY)",
              "DATTA MANDIR (SHIMPOLI)",
              "DATTA MANDIR (VAKOLA)",
              "DATTA PADA",
              "DATTA TEKDI - SHIV TEKADI",
              "DATTA WADI (KALWA)",
              "DATTAGURU DEVSTHAN",
              "DATTANI PARK",
              "DATTAPADA PHATAK",
              "DAULAT NAGAR BORIVALI",
              "DAULAT NAGAR S'CRUZ",
              "DAVA BAZAR",
              "DAWN MILL",
              "DEEPAK CINEMA",
              "DENA BANK KANDIVALI",
              "DEONAR BEST STAFF QUARTERS",
              "DEONAR DEPOT",
              "DEONAR FIRE BRIGADE CLY.",
              "DEONAR FIRE BRIGADE COLONY",
              "DEONAR MUNICIPAL CLY.",
              "DEONAR MUNICIPAL COLONY",
              "DEONAR POLICE STATION",
              "DEONAR VILLAGE",
              "DERASAR LANE",
              "DESAI MUNICIPAL HOSPITAL",
              "DEVI PADA",
              "DHAIRYAVAN CHOWK",
              "DHAKE COLONY",
              "DHANMILL NAKA",
              "DHANVANTARI HOSPITAL",
              "DHARAMSHI HALL",
              "DHARAVI DEPOT",
              "DHARAVI FLY OVER BRIDGE",
              "DHARAVI POLICE STATION",
              "DHARAVI T JUNCTION - TAPASE CHOWK",
              "DHARAVLI VILLAGE",
              "DHIRAJ ENCLAVE",
              "DHIRAJ SOCIETY",
              "DHOBI GHAT (BORIVALI)",
              "DHOBI GHAT (COLABA)",
              "DHOBI GHAT (CUFF PARADE)",
              "DHOBI GHAT (TROMBAY)",
              "DHOLKIA YAMUNA NAGAR",
              "DIAMOND INDUSTRIES",
              "DIAMOND MARKET BKC",
              "DIAMOND PARK",
              "DINDOSHI BUS STATION",
              "DINDOSHI PADA",
              "DIVA VILLAGE",
              "DIVINE CHILD HIGH SCHOOL",
              "DNYAN SADHANA COLLEGE",
              "DNYAN SARITA",
              "DNYAN SARITA (THANE)",
              "DNYANESHWAR NAGAR",
              "DNYANODAY VIDYALAYA",
              "DOCKYARD COLONY - KANJURMARG STATION",
              "DOCKYARD ROAD RAILWAY STATION",
              "DOMESTIC AIRPORT JUNCTION",
              "DOMESTIC AIRPORT TERMINAL 1-A",
              "DOMESTIC AIRPORT TERMINAL 1-B",
              "DOMNIC SCHOOL",
              "DON BOSCO SCHOOL (NERUL)",
              "DON BOSCO SCHOOL BORIVALI",
              "DON BOSCO SCHOOL MATUNGA",
              "DONGARI PADA",
              "DONGRE WADI BORIVALI",
              "DONGRI",
              "DONGRI JAIL",
              "DOORDARSHAN",
              "DOORDARSHAN COLONY",
              "DOSTI ACRES",
              "DR.AMBEDKAR CHOWK - INDIRA NAGAR",
              "DR.AMBEDKAR COLONY - 18TH ROAD",
              "DR.AMBEDKAR GARDEN",
              "DR.AMBEDKAR NAGAR BANDRA",
              "DR.AMBEDKAR NAGAR NO.2",
              "DR.AMBEDKAR ROAD BANDRA",
              "DR.AMBEDKAR STATUE (CHURCHGATE)",
              "DR.AMBEDKAR UDYAN (POWAI)",
              "Dr.BABASAHEB AMBEDKAR NAGAR (CHEMBUR)",
              "DR.BHADKAMKAR ROAD",
              "DR.COOPER HOSPITAL",
              "DR.DATTA SAMANT CHOWK - SAKI NAKA",
              "DR.K.B.HEDGEWAR CHOWK",
              "DR.M.IQBAL CHOWK",
              "DR.RAVINDRA KULKARNI CHOWK - SASMIRA",
              "DR.S.P.MUKHERJI CHOWK - MUSEUM",
              "DR.S.P.MUKHERJI GARDEN BORIVALI",
              "DR.SHIRODKAR HIGH SCHOOL",
              "DR.SUCHAK CHOWK",
              "DUDHSAGAR SOCIETY",
              "DUKES COMPANY (DEONAR)",
              "DUMPING GROUND - NIRANKARI BHAVAN",
              "DUMPING GROUND-NIRANKARI BHAVAN",
              "DUNNCAN COMPANY (MULUND)",
              "DURGA MAHESHWARI MANDIR",
              "DURGA NAGAR",
              "DURGA NAGAR KANDIVALI",
              "DURGAMATA MANDIR",
              "DWARKADHISH SOCIETY",
              "E",
              "E.S.I.S HOSPITAL (THANE)",
              "E.S.I.S HOSPITAL - MIDC POLICE STATION",
              "E.S.I.S.HOSPITAL (THAKUR VILLAGE)",
              "E.S.I.S.HOSPITAL KANDIVALI",
              "E.S.I.S.HOSPITAL MULUND",
              "E.S.I.S.LOCAL OFFICE POWAI",
              "EDEN WOOD (THANE)",
              "EKSAR KOLIWADA",
              "EKSAR VILLAGE",
              "EKTA BHOOMI COMPLEX",
              "EKTA NAGAR BHANDUP",
              "EKTA NAGAR KANDIVLI",
              "EKTA NAGAR MALAD",
              "EKTA SOCIETY MAROL",
              "EKTA VIVEK BLDG DAHIASR",
              "ELCO MARKET",
              "ELIA SARVAT JR.COLLEGE",
              "ELPHISTON STATION (WEST)",
              "EMPLOYMENT EXCHANGE (GHATKOPAR)",
              "ERANGAL VILLAGE",
              "ERLA",
              "ERLA MASJID",
              "ESIC NAGAR",
              "ESTRELLA BATTERY - SHAHU NAGAR",
              "EVERARD NAGAR",
              "EVERARD SOCIETY",
              "EVEREST CO.OP.SOCIETY",
              "EVERSHINE NAGAR",
              "FAITH (ANDHERI)",
              "FAMOUS STUDIO",
              "FAROOKH VIDYALAYA",
              "FATHER AGNEL ASHRAM",
              "FERRY WHARF",
              "FILMALAYA",
              "FILMISTAN",
              "FILTER PADA",
              "FIRE BRIGADE (GOREGAON)",
              "FIRE BRIGADE - KHARODI COLONY",
              "FIRE BRIGADE FORT",
              "FIRE BRIGADE JUNCTION (ANTOP HILL)",
              "FISH MARKET (DAHISAR)",
              "FISHER ROSE MOUNT COMPANY",
              "FIVE GARDENS",
              "FLORA HOTEL - WATUMAL ENGG COLLEGE",
              "FORENSIC LAB",
              "FOREST CLUB POWAI",
              "FORGN POST OFFICE FORT",
              "FOUR BUNGALOWS",
              "FOUR BUNGALOWS (MARKET)",
              "FREE PRESS JOURANAL MARG",
              "FREE PRESS JOURNAL HOUSE",
              "G.D.SOMANI SCHOOL",
              "G.S.COLONY",
              "G.T.HOSPITAL",
              "GADI ADDA",
              "GADKARI QUARRY",
              "GAGANDEEP",
              "GAI MUKH",
              "GAI WADI (GIRGAON)",
              "GALAXY VIEW BUILDING",
              "GALILIO BUILDING (CHANDIVALI)",
              "GAMMON HOUSE",
              "GANDHI BALMANDIR VIDYALAYA",
              "GANDHI MAIDAN WORLI",
              "GANDHI MARKET CHEMBUR",
              "GANDHI MARKET GHATKOPAR",
              "GANDHI MARKET MATUNGA",
              "GANDHI NAGAR (THANE)",
              "GANDHI NAGAR BANDRA",
              "GANDHI NAGAR KANDIVALI",
              "GANDHI NAGAR VIKHROLI",
              "GANDHI NAGAR WORLI",
              "GANDHIR VIDYALAYA",
              "GANESH BABAJI DHOND CHOWK",
              "GANESH CHOWK (NERUL)",
              "GANESH CHOWK KANDIVALI",
              "GANESH MANDIR - KASTUR PARK",
              "GANESH MANDIR CHARKOP",
              "GANESH MANDIR DAHISAR",
              "GANESH MANDIR MANKHURD",
              "GANESH NAGAR WADALA",
              "GANESH PADA",
              "GANESH SOCIETY",
              "GANESH SOCIETY (NERUL)",
              "GANESH TALKIES LALBAUG",
              "GANESHMURTY NAGAR POLICE STATION",
              "GANGA BHUWAN",
              "GANGA COMPLEX (MIRA ROAD)",
              "GANPAT PATIL NAGAR (DAHISAR)",
              "GARDEN COURT CIRCLE (THANE)",
              "GARIB NAGAR",
              "GARLIC COMPANY",
              "GARODIA NAGAR",
              "GARODIA PALACE",
              "GARTEN PADA",
              "GARTEN PADA NO.2",
              "GARWARE CHOWK",
              "GATEWAY OF INDIA",
              "GATEWAY PLAZA",
              "GAURAV RESIDENCY",
              "GAUTAM NAGAR - DEONAR ABATTOIR",
              "GAUTAM NAGAR ANDHERI",
              "GAUTAM NAGAR KANDIVALI",
              "GAUTAM NGR.-DEONAR ABATTOIR",
              "GAVDEVI CHOWK(SARSOLE)",
              "GAVDEVI MANDIR (THANE)",
              "GAVDEVI NAKA - MADHUKUN BUILDING",
              "GAVDEVI POLICE STATION",
              "GAWADE NAGAR",
              "GAWAN PADA",
              "GAWANGAON - REFINERIES",
              "GAWANPADA FIRE BRIGADE (MULUND EAST)",
              "GAZDAR BANDH",
              "GAZDAR MUNICIPAL SCHOOL",
              "GEETA NAGAR (COLABA)",
              "GEETANJALI BUILDING",
              "GELDA NAGAR",
              "GEN.A.K.VAIDYA MARG JUNCTION",
              "GHANSOLI NAKA",
              "GHANSOLI RAILWAY STATION",
              "GHANSOLI VILLAGE",
              "GHARKUL",
              "GHATI PADA MULUND",
              "GHATKOPAR DEPOT - CASEURINA",
              "GHATKOPAR PIPE LINE",
              "GHATKOPAR POLICE STATION",
              "GHATKOPAR POST OFFICE",
              "GHATKOPAR SONAPUR",
              "GHATKOPAR STATION (E)",
              "GHATKOPAR STATION (W)",
              "GHODBUNDER VILLAGE",
              "GHODBUNDER VILLAGE JUNCTION",
              "GHODDEO NAKA",
              "GHODPDEO",
              "GIRI SHIKHAR",
              "GIRIDHAR PARK",
              "GIRLS SCHOOL (DADAR)",
              "GLAXO COMPANY (THANE)",
              "GODREJ CHOWK",
              "GODREJ COMPANY (EAST)",
              "GODREJ COMPANY (WEST)",
              "GODREJ FOODS COMPANY - VEG.O",
              "GODREJ SOAP COMPANY (EAST)",
              "GOKHALE BRIDGE",
              "GOKHALE VIDYALAYA",
              "GOKHALE VIDYALAYA (KHARGHAR)",
              "GOKUL ANAND DAHISAR",
              "GOKUL GARDEN",
              "GOKUL HEAVAN",
              "GOKUL NAGAR (KANDIVALI)",
              "GOKUL NAGAR (THANE)",
              "GOKULDHAM MARKET",
              "GOL BUILDING",
              "GOL MANDIR",
              "GOLDEN CHEMICALS",
              "GOLDEN NEST",
              "GOLDEN TOBACCO",
              "GOMANT NAGAR",
              "GONDHALE WADI (THANE)",
              "GOODS SHED",
              "GOPAL BHUVAN",
              "GOPAL NAGAR",
              "GOPIKRISHNA PIRAMAL HOSPITAL",
              "GORAI BRIDGE",
              "GORAI CREEK",
              "GORAI DEPOT",
              "GOREGAON - OSHIWARA DEPOT",
              "GOREGAON BUS STATION (W)",
              "GOREGAON CHECK NAKA NO 1",
              "GOREGAON CHECK NAKA NO 2",
              "GOREGAON CHECK NAKA NO 3",
              "GOREGAON POLICE STATION",
              "GOREGAON STATION (E)",
              "GOREGAON TELEPHONE EXCHANGE",
              "GOTHIVALI VILLAGE - TEL EXCHANGE",
              "GOVANDI BUS STATION",
              "GOVANDI RAILWAY STN.",
              "GOVANDI STATION (W)",
              "GOVANDI STATION ROAD (E)",
              "GOVARDHAN NAGAR - BORSAPADA",
              "GOVARDHAN NAGAR - GABRIEL COMPANY",
              "GOVERNMENT LAW COLLEGE",
              "GOVIND NAGAR JUNCTION",
              "GOVT COLONY BLDG 10",
              "GOVT. COLONY - INDIAN.MEDICAL.ASS.CHOWK",
              "GRANT ROAD BRIDGE",
              "GRANT ROAD STATION (EAST)",
              "GRANT ROAD STATION (W)",
              "GREEN FIELDS",
              "GREEN HILL GATE NO.4",
              "GREEN LAWN ACADEMY",
              "GREEN PARK",
              "GREEN PARK MIRA ROAD",
              "GROVEL COMPANY",
              "GUJRAT SOCIETY - DAYALDAS ROAD",
              "GULAL WADI - YADNIK CHOWK",
              "GUNDECHA PROJECT",
              "GURU NANAK MARG JUHU",
              "GURU NANAK NAGAR",
              "GURU NANAK SCHOOL",
              "GURU TEGH BAHADUR NAGAR STATION",
              "GURUDWAR (MALVANI)",
              "GURUDWAR CHOWK",
              "GURUNANAK VIDYALAYA",
              "GYMKHANA (MARINE LINES)",
              "H.P.NAGAR",
              "HAFFKINE INSTITUTE",
              "HAKOBA (KALA CHOWKEY)",
              "HANUMAN CHOWK (MULUND)",
              "HANUMAN MANDIR (TULSHET PADA)",
              "HANUMAN MANDIR - D'SILVA SCHOOL",
              "HANUMAN MANDIR CHARKOP",
              "HANUMAN MANDIR GHATKOPAR",
              "HANUMAN NAGAR (BHANDUP)",
              "HANUMAN NAGAR (NAHUR)",
              "HANUMAN NAGAR DINDOSHI",
              "HANUMAN NAGAR KANDIVALI",
              "HANUMAN ROAD",
              "HANUMAN SOCIETY BLDG NO.5",
              "HANUMAN TEKDI - CHOGLE NAGAR",
              "HARE RAM HARE KRISHNA MANDIR",
              "HARI BHAKTI DOVEL COMPANY",
              "HARI NIKETAN SOCIETY",
              "HARI NIWAS",
              "HARI OM NAGAR (SOHAM SELES BLDG)",
              "HARI OM NAGAR MAIN GATE",
              "HARIDAS NAGAR",
              "HARIYALI VILLAGE - LINK ROAD",
              "HASRAT MOHANI CHOWK",
              "HDFC COLONY",
              "HELEN KELLAR SOCIETY",
              "HELEN-JOE MUN.GARDEN",
              "HEMA INDUSTRIAL ESTATE",
              "HEMA PARK",
              "HEMGIRI SOCIETY - GANESH MANDIR",
              "HIGHLAND GARDEN OSHIWARA",
              "HIGHLAND PARK MULUND",
              "HIGHWAY APARTMENTS",
              "HILL ROAD GARDEN",
              "HIND RECTIFIER CORPN",
              "HINDMATA CINEMA",
              "HINDU CEMETRY",
              "HINDUSTAN CHOWK",
              "HINDUSTAN COMPANY",
              "HINDUSTAN NAKA - CHARANSINGH CHOWK",
              "HINDUSTAN PETROLEUM SEWREE",
              "HINDUSTAN PETROLUM COLONY",
              "HIRA PARK",
              "HIRANANDANI",
              "HIRANANDANI (KHARGHAR)",
              "HIRANANDANI ESTATE GATE",
              "HIRANANDANI GARDEN",
              "HIRANANDANI POWAI BUS STATION",
              "HIRANANDANI TEL. EXCHANGE",
              "HITCO",
              "HOECHST COMPANY - NIRMAL LIFE STYLE",
              "HOLY ANGLE'S HIGH SCHOOL",
              "HOLY CROSS ROAD",
              "HOLY CROSS ROAD - PREMIER COMPANY",
              "HOLY CROSS SCHOOL",
              "HOLY FAMILY HOSPITAL",
              "HOLY SPIRIT HOSPITAL",
              "HOME GUARD TRAINING SCHOOL",
              "HORNIMAN CIRCLE - FORT",
              "HOUSING COLONY DINDOSHI",
              "HP OFFICERS QRTS",
              "HPCL BANDRA",
              "HUMA TALKIES",
              "HUTATMA CHOWK",
              "HYDRABAD ESTATE",
              "HYPER CITY GOREGAON W",
              "I.B.P.COMPANY",
              "I.C.COLONY",
              "I.C.I. COMPANY",
              "I.C.L.SCHOOL",
              "I.E.S.SCHOOL,JVLR",
              "I.E.S.VIDYALAYA",
              "I.I.T.MAIN GATE",
              "I.I.T.MARKET",
              "I.N.S.HAMALA MAIN GATE",
              "I.R.B.COMPLEX(POWAI)",
              "ICICI BANK BKC",
              "ICICI BANK-SINHGAD COLLEGE (CHANDIVALI)",
              "IJMIMA",
              "IMAX ADLABS",
              "INCOME TAX COLONY JOGESHWARI",
              "INCOME TAX OFFICE BKC",
              "INCOME TAX OFFICE MARINE LINES",
              "INDIAN BANK (HIRANANDANI THANE)",
              "INDIAN EDUCATION SOCIETY SCHOOL",
              "INDIAN HUME PIPE COMPANY",
              "INDIAN OIL DEPOT",
              "INDIAN OIL NAGAR ANDHERI",
              "INDIAN OIL NAGAR SH'NAGAR",
              "INDIRA DOCK",
              "INDIRA NAGAR (SEWREE)",
              "INDIRA NAGAR - KHALAI VILLAGE V'VIHAR",
              "INFINITY I.T.PARK",
              "INORBIT MALL",
              "INS ASHWINI HOSPITAL",
              "INSPECTOR KAKLIS CHOWK",
              "INTER STATE BUS STATION",
              "INTERFACE BLDG-16",
              "IRANI BRIDGE",
              "IRANI WADI - RAMDEV ASHRAM",
              "ISHWAR NAGAR BHANDUP",
              "ISHWARBHAI PATEL ROAD",
              "ISMAIL YUSUF COLLEGE",
              "J.B.NAGAR",
              "J.J.HOSPITAL NURSING SOCIETY",
              "J.MEHTA MARG",
              "J.V.G.FINANCE COMPANY",
              "J.V.P.D.BUS STATION",
              "JACKERIA BUNDER",
              "JAFRI ENGLISH SCHOOL",
              "JAFRI SCHOOL",
              "JAGARDEV COMPOUND",
              "JAGAT SATGURU INDUSTRIAL COLONY",
              "JAGDUSHA NAGAR",
              "JAGRUTI NAGAR",
              "JAI BHIM NAGAR",
              "JAI GANESH TALKIES MULUND",
              "JAI MAHAKALI MANDIR",
              "JAI MAHARASHTRA NAGAR",
              "JAIHIND CINEMA",
              "JAIN MANDIR (OM NAGAR) ANDHERI",
              "JAIN MANDIR BHAYANDAR",
              "JAIN MANDIR GHATKOPAR",
              "JAIN MANDIR GHODBUNDER",
              "JAIN MANDIR GOREGAON",
              "JAIN MANDIR KANDIVALI",
              "JAIN MANDIR MULUND EAST",
              "JAIN SOCIETY",
              "JAKHADEVI - DADAR POLICE STATION",
              "JAL-VAYU VIHAR",
              "JALVAYU VIHAR (KHARGHAR)",
              "JAMA MASJID (MIRA ROAD)",
              "JAMA MASJID MANKHURD",
              "JAMBHUL PADA",
              "JAMBLI MOHALLA",
              "JAMMU & KASHMIR BANK MIRA ROAD",
              "JANAKI RESIDENCY (BHAYANDAR)",
              "JANASHAKTI POLICE CHOWKEY",
              "JANATA COLONY-SHIV MANDIR",
              "JANATA DAIRY",
              "JANATA MARKET BHANDUP",
              "JANKALYAN NAGAR",
              "JANKALYAN NAGAR POLICE STATION",
              "JANKI DEVI VIDYALAYA",
              "JARI MARI",
              "JASLOK HOSPITAL",
              "JAWAHAR NAGAR",
              "JAY COACH S.R.P.CAMP",
              "JAY COACH - S.R.P.CAMP",
              "JAY GANGA",
              "JAY SHASTRI NAGAR",
              "JEEVAN BIMA NAGAR",
              "JEEVAN JYOTI ENGLISH SCHOOL",
              "JEEVAN NAGAR",
              "JEEVAN VIMA MARG",
              "JIJAMATA BHONSLE MARG JUNCTION",
              "JIJAMATA MUNICIPAL SCHOOL",
              "JIJAMATA NAGAR MAHUL",
              "JIJAMATA NAGAR WORLI",
              "JIJAMATA UDYAN",
              "JIJAMATA VIDYALAYA",
              "JITENDRA MARG",
              "JIVALA PADA",
              "JIVAN NAGAR",
              "JOGESHWARI BUS STATION",
              "JOGESHWARI POLICE STATION",
              "JOGESHWARI STATION (E)",
              "JOGESHWARI STATION (WEST)",
              "JOGESHWARI TABELA",
              "JOGESHWARI TELEPHONE EXCHANGE",
              "JOGESHWARI VIKHROLI LINK ROAD",
              "JOHAR CHOWK",
              "JOHN BACKER",
              "JOHN BAPTIST ROAD",
              "JOHNSON COMPANY MULUND",
              "JU CHANDRA HOUSING SOCIETY",
              "JUBILEE MILLS",
              "JUHU BEACH",
              "JUHU BUS STATION",
              "JUHU HOTEL",
              "JUHU KOLIWADA",
              "JUHU PRABHAT",
              "JUHU SHOPPING CENTRE",
              "JUHU TARA",
              "JUHU VILLAGE",
              "JUI NAGAR STATION ( HERDILLA COMPANY)",
              "JUINAGAR RAILWAY STATION",
              "JUINAGAR SECTOR-25",
              "JUIPADA VILLAGE",
              "JUMBO DARSHAN",
              "JUNGLE MANGAL ROAD",
              "JUNGLESHWAR MAHADEO MANDIR",
              "K.C.COLLEGE",
              "K.C.COMPANY",
              "K.E.M.HOSPITAL",
              "K.V.YADAV CHOWK - LOWER PAREL",
              "KACH PADA",
              "KACH WADI (DEONAR)",
              "KADAM PADA",
              "KAILASH INDUSTRIAL ESTATE",
              "KAJU PADA - GANESH MAIDAN - GHATKOPAR",
              "KAJU PADA BORIVALI",
              "KAJU PADA GHODBUNDER",
              "KALA CHOWKY POLICE STATION",
              "KALA MARUTI MANDIR",
              "KALA NAGAR",
              "KALA VIDYALAYA (MALVANI)",
              "KALAKILLA",
              "KALAMBOLI BUS STATION",
              "KALAMBOLI FIRE BRIGADE",
              "KALBADEVI",
              "KALIDAS NATYAGRUH",
              "KALINA",
              "KALINA MARKET",
              "KALPANA CHAWLA CHOWK",
              "KALPANA TALKIES",
              "KALPTARU ESTATE",
              "KALWA BRIDGE",
              "KALYAN NAGAR (MAROL)",
              "KAMAL BAUG - 14TH BUNGALOWS",
              "KAMAL TOWING COMPANY",
              "KAMAL VIHAR SPORTS COMPLEX",
              "KAMANI",
              "KAMANI OIL INDUSTRIES",
              "KAMGAR NAGAR",
              "KAMGAR STADIUM",
              "KAMLA MILL",
              "KAMLA NEHRU PARK",
              "KAMLISTAN STUDIO",
              "KAMOTHE VILLAGE - MANSAROVAR",
              "KAMRAJ NAGAR",
              "KAMRAJ VIDYALAYA (DHARAVI)",
              "KANDAR PADA",
              "KANDAR PADA (RUSHI COMPLEX EXT)",
              "KANDAR PADA BUS STATION",
              "KANDIVALI BUS STATION ( E )",
              "KANDIVALI ESTATE - GANESH NAGAR",
              "KANDIVALI STATION (W)",
              "KANDIVALI TELEPHONE EXCHANGE",
              "KANDIVALI VILLAGE",
              "KANE NAGAR",
              "KANHERI CAVES",
              "KANHERI CAVES BASE",
              "KANJUR MARG VILLAGE",
              "KANJUR VIILLAGE",
              "KANJURMARG STATION (W)",
              "KANNAMWAR NAGAR",
              "KANNAMWAR NAGAR 2",
              "KANNAMWAR NAGAR BUILDING - 124",
              "KANNAMWAR NAGAR BUILDING - 150",
              "KANNAMWAR NAGAR BUILDING - 175",
              "KANNAMWAR NAGAR BUILDING - 188",
              "KANNAMWAR NAGAR HOSPITAL",
              "KANNAMWAR NAGAR NO 1",
              "KAPADA BAZAR",
              "KAPADIA NAGAR",
              "KAPIL BUDHHA VIHAR (KALINA)",
              "KAPOLE NIWAS - J.N.VARMA CHOWK",
              "KAPUR BAWDI",
              "KARIM BUNGALOWS",
              "KARMAVEER DADASAHEB GAIKWAD NAGAR",
              "KARTVYA NAGAR",
              "KASAR VADAVALI",
              "KASHI MIRA",
              "KASHI VILLAGE",
              "KASHIMIRA TELEPHONE EXCHANGE",
              "KASTURBA GANDHI CHOWK",
              "KASTURBA GANDHI HOSPITAL",
              "KASTURI ESTATE",
              "KASTURI VIDYALAYA",
              "KAVERI MAHIMA SOCIETY",
              "KELKAR COLLEGE",
              "KENDRIYA VIDYALAYA AKSA",
              "KENDRIYA VIHAR (KHARGHAR)",
              "KENI VIDYALAYA",
              "KETAKI PADA",
              "KEVA FRAGRANES",
              "KHADI BHANDAR",
              "KHALSA COLLEGE",
              "KHAMBATA LANE",
              "KHAMBEKAR STREET",
              "KHAR",
              "KHAR 14TH ROAD",
              "KHAR DANDA",
              "KHAR POLICE STATION",
              "KHAR STATION (W)",
              "KHAR TELEPHONE EXCHANGE",
              "KHARGHAR STATION SUBWAY",
              "KHARI GAON",
              "KHARIGAON NAKA",
              "KHARODI VILLAGE",
              "KHED GALLI",
              "KHER WADI - CHETNA COLLEGE",
              "KHER WADI JUNCTION",
              "KHER WADI POLICE STATION",
              "KHERANI BAUG",
              "KHET WADI",
              "KHINDI PADA",
              "KHIRA NAGAR",
              "KHODADAD CIRCLE",
              "KHOPAT S.T.TERMINUS",
              "KHOT ROAD",
              "KIDWAI NAGAR",
              "KIDWAI ROAD POLICE STATION",
              "KINGSTON SEZ (POWAI)",
              "KIRTI COLLEGE - INDIA UNITED MILL",
              "KISAN NAGAR JUNCTION",
              "KOHINOOR COMPLEX BLDG-3",
              "KOHINOOR HOSPITAL",
              "KOHINOOR SRA COLONY",
              "KOKAN NAGAR BHANDUP",
              "KOKAN VIKAS MANDAL",
              "KOKANI PADA DAHISAR",
              "KOKANI PADA EXTENSION",
              "KOKANI PADA MALAD",
              "KOLBAD",
              "KONARK APARTMENT",
              "KONDIVTE CAVES - MAHAKALI CAVES",
              "KONKAN BHAVAN",
              "KOPAR KHAIRANE",
              "KOPAR KHAIRANE RAILWAY STATION",
              "KOPARI COLONY",
              "KOPARI PADA",
              "KOPARI TELEPHONE EXCHANGE",
              "KORA KENDRA",
              "KORBA MITHAGAR",
              "KRANTI NAGAR ANDHERI",
              "KRANTI NAGAR KANDIVALI",
              "KRISHNA BAUG - FINE ARTS AUDITORIUM",
              "KRISHNA BUILDING",
              "KRISHNA LEELA HOUSING SOCIETY",
              "KRISHNA NAGAR",
              "KRISHNA VATIKA",
              "KRUPA BUILDING",
              "KULKARNI WADI",
              "KUMBHAR WADA",
              "KUMBHAR WADA (DHARAVI)",
              "KUNCHI KURVE NAGAR",
              "KURAR POLICE STATION",
              "KURAR VILLAGE",
              "KURAR VILLAGE EXTENSION",
              "KURLA BUS STATION ( E )",
              "KURLA DEPOT",
              "KURLA LEVEL CROSSING",
              "KURLA NAGRIK SAHAKARI BANK",
              "KURLA POST OFFICE",
              "KURLA S.T.DEPOT",
              "KURLA STATION ( W )",
              "L & T GATE NO.6",
              "L&T INFOTECH",
              "L.I.C.COLONY BANDRA",
              "L.I.C.OFFICE BORIVALI",
              "L.I.C.OFFICERS TRNING CNTR BORIVALI",
              "LAKSHYACHANDI SOCIETY",
              "LAL BAHADUR SHASTRI COLLEGE",
              "LAL DONGAR",
              "LALA LAJPATRAI COLLEGE",
              "LALJIPADA POLICE CHOWKY",
              "LALLUBHAI COMPOUD POLICE CHK.EY",
              "LALLUBHAI COMPOUD POLICE CHOWKEY",
              "LAXMI INDUSTRIAL ESTATE",
              "LAXMI NAGAR",
              "LAXMI PARK MIRA ROAD",
              "LAXMI TOWER BKC",
              "LAXMINARAYAN RESIDENCY (THANE)",
              "LIBERTY GARDEN",
              "LIBRA SOCIETY",
              "LION'S CLUB ( GUNDAVLI )",
              "LION'S GATE",
              "LION'S PARK",
              "LOCAL SELF GOVT OFFICE (BANDRA)",
              "LODHA COMPLEX (MIRA ROAD)",
              "LODHA COMPLEX (THANE)",
              "LOHA BHAVAN",
              "LOK PURAM",
              "LOKIM COMPANY",
              "LOKMANYA NAGAR (THANE)",
              "LOKMANYA TILAK CHOWK",
              "LOKMANYA TILAK HOSPITAL",
              "LOKMANYA TILAK NAGAR ASALPHA",
              "LOKMANYA TILAK NAGAR CHEMBUR",
              "LOKMANYA TILAK NAGAR GOREGAON",
              "LOKMANYA TILAK TERMINUS",
              "LOKMANYA TILAK VIDYALAYA",
              "LOKMAT OFFICE (MHAPE)",
              "LOTUS HOSPITAL",
              "LOUIS WADI",
              "LOWER PAREL STATION",
              "LOWER PAREL WORKSHOP",
              "LUBE INDIA COMPANY",
              "LUCKY HOTEL",
              "M.GANDHI SWIMMING POOL KANDIVALI",
              "M.GANDHI VIDYA MANDIR BANDRA",
              "M.GANDHI VIDYALAYA JOGESHWARI",
              "M.H.B.COLONY (GORAI)",
              "M.H.B.COLONY (JOGESHWARI)",
              "M.H.B.POLICE STATION",
              "M.I.D.C.ELECTRONIC SADAN",
              "M.I.G.COLONY (KALA NAGAR)",
              "M.M.R.D.A CLY (EXTN) MAHUL",
              "M.M.R.D.A CLY BLDG NO 31",
              "M.M.R.D.A CLY BLDG NO 39",
              "M.M.R.D.A COLONY (MAHUL)",
              "M.M.R.D.A-PAY&PARK BKC",
              "M.M.R.D.A.-FAMILY COURT BKC",
              "M.P.CHOWK MULUND - MULUND (W) CHECK NAKA BUS STATION - R Mall",
              "M.S.E.B.OFFICE KOPAR KHAIRANE",
              "M.T.PARK (COLABA)",
              "MACHHALIMAR VERSOVA",
              "MACHHIMAR NAGAR MAHIM",
              "MADH BEACH - MADH CHURCH",
              "MADH JETTY",
              "MADH MARKET",
              "MADH SONAPUR",
              "MADH TEMPLE",
              "MADHANI CIRCLE (THANE)",
              "MADHAV NAGAR",
              "MADHU PARK",
              "MADHUR COLONY",
              "MADHUSHREE (MIRA ROAD)",
              "MADINA MANZIL",
              "MADKEBUWA CHOWK - PAREL",
              "MAFATLAL MILL",
              "MAFATLAL PARK",
              "MAFCO MARKET",
              "MAGATHANE DEPOT",
              "MAGATHANE TEL EXCHANGE",
              "MAHA VISHNU - SAMRAT HOTEL",
              "MAHALAXMI MANDIR (DEONAR)",
              "MAHALAXMI RACE COURSE",
              "MAHALAXMI STATION",
              "MAHALAXMI TEMPLE",
              "MAHANANDA DAIRY",
              "MAHANT ROAD",
              "MAHAPE GAON",
              "MAHAPE NAKA",
              "MAHARAJA BHAVAN",
              "MAHARANA PRATAP CHOWK MAZGAON",
              "MAHARASHTRA KATA ASALPHA",
              "MAHARASHTRA KATA MAROL",
              "MAHARASHTRA NAGAR (THANE)",
              "MAHARASHTRA NAGAR BHANDUP",
              "MAHARASHTRA NAGAR BORIVALI",
              "MAHARASHTRA NAGAR SH'NAGAR",
              "MAHARASHTRA STATE CO-OP BANK (VASHI)",
              "MAHARASHTRA WEIGHT BRIDGE SION",
              "MAHARASTHRA BANK OSHIWARA",
              "MAHARSHI ARVIND CHOWK - PAANCH RASTA",
              "MAHATMA GANDHI HOSPITAL",
              "MAHATMA PHULE BHAVAN (VIDYA NAGARI)",
              "MAHATMA PHULE MARKET",
              "MAHATMA PHULE NAGAR",
              "MAHAVIR DHAM POISAR",
              "MAHAVIR EDUCATIONAL TRUST",
              "MAHAVIR NAGAR",
              "MAHAVIR NAGAR EXTENSION - PARIJAT SOCIETY",
              "MAHESHWARI DHAM",
              "MAHESHWARI NAGAR",
              "MAHESHWARI UDYAN",
              "MAHIM",
              "MAHIM ( PARADISE )",
              "MAHIM BUS STATION",
              "MAHIM KOLIWADA",
              "MAHIM PHATAK",
              "MAHIM PHATAK (EAST)",
              "MAHIM STATION ( W )",
              "MAHINDRA COMPANY (BHAD COLONY)",
              "MAHUL MARKET",
              "MAHUL VILLAGE",
              "MAITRAIYA SOCIETY",
              "MAITRI PARK",
              "MAJAS DEPOT - SHYAM NAGAR",
              "MAJESTIC CINEMA",
              "MAJIWADA",
              "MAKER TOWER",
              "MAKHMALI TALAO",
              "MALAD BUS DEPOT",
              "MALAD INDUSTRIAL ESTATE",
              "MALAD STATION (E)",
              "MALAD STATION (W)",
              "MALATI COTTAGE",
              "MALBAR HILL POST OFFICE",
              "MALLET BUNDER",
              "MALVANI AKASHWANI",
              "MALVANI BLOCK NO 5",
              "MALVANI BLOCK NO 6",
              "MALVANI BLOCK NO 7",
              "MALVANI CHURCH - MALVANI VILLAGE",
              "MALVANI DEPOT - GAIKWAD NAGAR",
              "MAMA HOTEL",
              "MAN PADA",
              "MANASI PARADISE",
              "MANAV KALYAN KENDRA",
              "MANDALA",
              "MANDLI TALAO",
              "MANDVI POST OFFICE",
              "MANEKJI COOPER SCHOOL",
              "MANEKLAL MUNICIPAL SCHOOL",
              "MANGALDAS MARKET",
              "MANGATRAM PETROL PUMP",
              "MANISHA NAGAR (KALWA)",
              "MANKHURD OCTROI NAKA",
              "MANKHURD STATION",
              "MANKHURD STATION ( NORTH )",
              "MANKHURD STATION ROAD (S)",
              "MANOBINA APARTMENTS",
              "MANSUKH DYEING COMPANY",
              "MANTRALAYA",
              "MARATHA COLONY",
              "MARATHI VIDNYAN PARISHAD",
              "MARATHI VIDYALAYA (GHATKOPAR-E)",
              "MARATHON CHOWK - TEEN HATH NAKA",
              "MARAWALI CHURCH",
              "MARIAMMAN MANDIR",
              "MARINE DRIVE",
              "MARINE LINES RAILWAY STATION",
              "MAROL DEPOT",
              "MAROL LIONS CLUB",
              "MAROL MAROSHI BUS STATION",
              "MAROL NAKA",
              "MAROL PIPE LINES",
              "MAROL VILLAGE",
              "MAROSHI NAKA - PICNIC POINT",
              "MARSHAL WADI",
              "MARVA INDUSTRIAL ESTATE",
              "MARVE - ESSEL WORLD",
              "MARVE ROAD NAKA - SWAMI SHIVANAND CHOWK",
              "MARVE VILLAGE",
              "MARY IMMACULATE SCHOOL",
              "MASINA HOSPITAL - RUSTOM BAUG",
              "MASRANI ESTATE",
              "MASTAN TALAO",
              "MASTER WADI",
              "MATHADI BHAVAN - COMMODITY EXCHANGE",
              "MATOSHRI SANKALP",
              "MATRUCHAYA",
              "MATUNGA LABOUR CAMP",
              "MATUNGA POLICE STATION",
              "MATUNGA RAILWAY PHATAK (E)",
              "MATUNGA STATION (E)",
              "MATUNGA STATION (W)",
              "MAYORS BUNGALOW - SHIVAJI PARK (CADEL ROAD)",
              "MAYUR CINEMA",
              "MAYUR NAGAR",
              "MAZGAON COURT",
              "MAZGAON DOCK (MAHUL)",
              "MAZGAON DOCK (MAZGAON)",
              "MCA COMPLEX BKC",
              "MEENATAI THAKRE MAIDAN - ANACIN COMPANY",
              "MEGA MART (VASHI)",
              "MEGHWADI NAKA",
              "MEHRABAD BAUG",
              "MEHTAB LANE",
              "MERCHANT BROTHERS",
              "MERCURY BUILDING",
              "MERIND COMPANY",
              "METRO PLAYING CARDS",
              "MGM HOSPITAL - PANVEL NAKA",
              "MHADA BUS STATION (MULUND-E)",
              "MHADA COLONY (CHANDIVALI)",
              "MHADA COLONY (HIRANANDANI)",
              "MHADA COLONY (KANDIVALI)",
              "MHADA COLONY (MALVANI)",
              "MHADA COLONY (SHIMPOLI)",
              "MHADA COLONY KURLA",
              "MHADA COLONY MAJAS",
              "MHADA COLONY PRATIKSHA NAGAR",
              "MHADA OFFICE (MULUND-E)",
              "MHATRE PEN COMPANY",
              "MICHAEL WADI",
              "MIDC - PASSPORT OFFICE",
              "MILAN SUB WAY",
              "MILAN TALKIES",
              "MILAP TALKIES",
              "MILIND NAGAR (JVLR)",
              "MILIND NAGAR BHANDUP",
              "MILIND NAGAR GHATKOPAR",
              "MILITARY CAMP",
              "MILITARY CANTEEN - CIPLA",
              "MILITARY OUTPOST",
              "MILLAT NAGAR",
              "MILLENNIUM BUSINESS PARK",
              "MINARA MASJID",
              "MINERVA TALKIES",
              "MINI LAND SOCIETY",
              "MINI NAGAR",
              "MIRA GAOTHAN",
              "MIRA ROAD MARKET",
              "MIRA ROAD POLICE STATION",
              "MIRA ROAD SECTOR-10",
              "MIRA ROAD STATION ( E)",
              "MIRA-BHAYANDAR MUNICIPAL HEAD OFFICE",
              "MITH CHOWK MALAD",
              "MITH CHOWKY MALAD",
              "MITHA NAGAR",
              "MITHAGAR (MULUND-E)",
              "MITHAGAR MULUND",
              "MITHIBAI COLLEGE",
              "MITTAL ESTATE",
              "MODEL TOWN (MAJAS)",
              "MODEL TOWN (MULUND)",
              "MODERN BAKERY - RESERVIOR",
              "MODERN USHA COLONY",
              "MOHILI VILLAGE",
              "MOHITE PATIL NAGAR",
              ",MOMIN NAGAR",
              "MONGINIS CAKE COMPANY",
              "MORA VILLAGE",
              "MORARJI NAGAR",
              "MORE MALL",
              "MOTI CINEMA",
              "MOTI MAHAL",
              "MOTILAL NAGAR BLOCK NO 8",
              "MOTILAL NAGAR NO 2",
              "MOTILAL NAGAR POST OFFICE",
              "MOUNT CARMEL CHURCH - LILAWATI HOSPITAL",
              "MOUNT MARY STEPS (MUNICIPAL GARDEN)",
              "MOVIE STAR TALKIES",
              "MOVIE TIME CINEMA",
              "MPSC-UPSC TRAINING CENTRE (BANDRA)",
              "MRUCHHALA COLLEGE",
              "MT.POINSUR CHURCH",
              "MUKESH CHOWK",
              "MUKTAI NAGAR (THANE)",
              "MUKUND COMPANY - P.W.D.OFFICE",
              "MULLA BAUG",
              "MULUND AIROLI TOLL NAKA",
              "MULUND CHECK NAKA (E)",
              "MULUND COLONY",
              "MULUND COURT",
              "MULUND DEPOT",
              "MULUND GARDEN",
              "MULUND GOREGAON LINK ROAD",
              "MULUND SONAPUR",
              "MULUND STATION (E)",
              "MULUND STATION (W)",
              "MUMBAI C.S.M.T.",
              "MUMBAI CENTRAL DEPOT",
              "MUMBAI CENTRAL STATION",
              "MUMBAI CENTRAL STATION (WEST)",
              "MUMBAI GYMKHANA",
              "MUNICIPAL COLONY SECTOR-B",
              "MUNICIPAL COLONY SECTOR-D",
              "MUNICIPAL COLONY VIKHROLI",
              "MUNICIPAL COLONY WORLI",
              "MUNICIPAL COMMISSIONER BUNGALOWS",
              "MUNICIPAL DISPENSARY S'CRUZ",
              "MUNICIPAL GARAGE (WORLI)",
              "MUNICIPAL GARDEN (BORIVALI)",
              "MUNICIPAL GARDEN (CHEMBUR)",
              "MUNICIPAL GARDEN - BAND STAND",
              "MUNICIPAL GARDEN VIKHROLI",
              "MUNICIPAL GUMPHA SCHOOL",
              "MUNICIPAL HOSPITAL (PARK SITE)",
              "MUNICIPAL HOSPITAL DAHISAR",
              "MUNICIPAL HOSPITAL MULUND",
              "MUNICIPAL LIBRARY CHEMBUR",
              "MUNICIPAL MARKET - SAIBABA MANDIR",
              "MUNICIPAL OFFICE - BHABHA HOSPITAL",
              "MUNICIPAL PUMPING CENTRE (MALVANI)",
              "MUNICIPAL PUMPING CENTRE (SHIMPOLI)",
              "MUNICIPAL SCHOOL CHEMBUR",
              "MUNICIPAL SCHOOL MALAD",
              "MUNICIPAL SCHOOL MULUND",
              "MUNICIPAL WARD OFFICE - AMBEDKAR GARDEN",
              "MUSTAFA BAZAR - SAVLYA TANDEL CHOWK",
              "N.C.P.A.",
              "N.G.PARK (RAWAL PADA)",
              "N.L.COMPLEX",
              "N.L.VIDYALAYA",
              "N.M.JOSHI MARG POLICE STATION",
              "N.S.C. COMPOUND",
              "NABARD NAGAR",
              "NADKARNI PARK",
              "NAFA",
              "NAGARI NIVARA VIDYALAY",
              "NAGARI NIWARA 1 & 2",
              "NAGARI NIWARA BLDG-16",
              "NAGARI NIWARA NO.5",
              "NAGBABA MANDIR (DYNALOG COMPANY)",
              "NAGPADA POLICE STATION",
              "NAHUR RAILWAY STATION",
              "NAHUR RAILWAY STATION (EAST)",
              "NAHUR VILLAGE - MEHUL CINEMA",
              "NAIDU COLONY",
              "NAIGAON POLICE COLONY",
              "NAIK NAGAR",
              "NAIR HOSPITAL",
              "NALANDA PEDDAR ROAD",
              "NALANDA SOCIETY GHATKOPAR",
              "NAMASKAR",
              "NANA CHOWK",
              "NANA WADI (MERAJ MASJID)",
              "NANA-NANI PARK",
              "NANAVATI HOSPITAL",
              "NANEPADA JUNCTION (MITHAGHAR)",
              "NANSEY COLONY",
              "NARAYAN DABHOLKAR MARG",
              "NARAYAN GURU H'SCHOOL",
              "NARAYAN NAGAR (GHATKOPAR)",
              "NARAYAN PUJARI NAGAR",
              "NARDAS NAGAR",
              "NARENDRA APARTMENT",
              "NARIMAN POINT FIRE BRIGADE",
              "NARMADESHWAR MANDIR",
              "NARSIPADA",
              "NATASHA TOWER",
              "NATHU JOMA PATIL CHOWK (SANPADA)",
              "NATIONAL COLLEGE",
              "NATIONAL DAIRY",
              "NATIONAL HOSPITAL",
              "NATRAJ STUDIO",
              "NATURE PARK - P.M.G.P.COLONY - DHARAVI",
              "NAV SOCIETY",
              "NAVA GAON",
              "NAVARANG HOTEL (KHARGHAR)",
              "NAVGHAR NAKA",
              "NAVGHAR ROAD",
              "NAVJEEVAN NAGAR",
              "NAVJEEVAN SOCIETY (KURLA)",
              "NAVJEEVAN SOCIETY CHEMBUR",
              "NAVJEEVAN SOCIETY TARDEO",
              "NAVJIVAN VIDYAMANDIR (BHANDUP)",
              "NAVPADA",
              "NAVRANG TALKIES",
              "NAVSENA GATE - KIROL VILLAGE",
              "NAVY NAGAR COLABA",
              "NAVY NAGAR MALAD",
              "NAWAB TANK MARG",
              "NEELKAMAL NAKA",
              "NEHRU LIBRARY (VIDYANAGARI)",
              "NEHRU NAGAR",
              "NEHRU PLANETARIUM",
              "NEIGHBOUR HOOD SOCIETY",
              "NELCO",
              "NELCO MAHAPE",
              "NERUL BUS STATION",
              "NERUL GYMKHANA",
              "NERUL NAKA",
              "NERUL RAILWAY STATION (NORTH)",
              "NERUL RAILWAY STATION (SOUTH)",
              "NERUL SECTOR-2",
              "NERUL SECTOR-42",
              "NERUL SECTOR-46-48",
              "NERUL VILLAGE",
              "NETAJI SUBHASHCHANDRA BOSE KRIDANGAN",
              "NEW AGRIPADA",
              "NEW CUSTOM HOUSE",
              "NEW D.N.NAGAR",
              "NEW ERA TALKIES",
              "NEW GAUTAM NAGAR",
              "NEW HINDUSTAN DORR",
              "NEW INDIA QUARTERS",
              "NEW INDIRA DOCK",
              "NEW LINK ROAD JUNCTION",
              "NEW NAGPADA",
              "NEW QUARTERS (CHAKAL CIG. FACTORY)",
              "NEW SHAKTI MILL",
              "NEW SIDDHARTH NAGAR",
              "NEW YELLOW GATE",
              "NEW ZEALAND HOSTEL (CENTRAL DAIRY)",
              "NILAM NAGAR BLDG NO 3",
              "NILAM NAGAR PHASE 2",
              "NILDHARA BUILDING",
              "NILKANTH VALLEY",
              "NIMBOR PADA",
              "NIMKAR SOCIETY",
              "NIRLON SOCIETY",
              "NIRMAL BUILDING",
              "NIRMAN BHAVAN",
              "NITIE",
              "NITIN COMPANY",
              "NITYANAND NAGAR",
              "NOOR BAUG",
              "NOORANI MASJID (PATHAN WADI)",
              "NORTH BOMBAY SCHOOL",
              "NOVELTY CINEMA - DR BHADKAMKAR ROAD",
              "NOVELTY SILK MILLS",
              "O.N.G.C.COLONY ( DINDOSHI )",
              "OBEROY WOODS",
              "ODEON CINEMA",
              "OLD AGRA ROAD",
              "OLD CUSTOM HOUSE",
              "OLD KHAR",
              "OLD PUSHPA PARK",
              "OM BUILDING",
              "OM NAGAR (WARE HOUSE)",
              "OMKARESHWAR MANDIR",
              "ORDINANCE DEPOT ( REAY ROAD - E )",
              "ORDINANCE FACTORY",
              "ORIENTAL BANK - SAMARTH NAGAR MARKET",
              "ORKAY MILLS",
              "ORLEM CHURCH",
              "ORLEM POST OFFICE",
              "ORLEM WELL",
              "OSHIWARA BRIDGE",
              "OSHIWARA MUNICIPAL HOSPITAL",
              "OSHIWARA POLICE STATION",
              "OSWAL PARK",
              "OTIS COMPANY",
              "OUR LADY OF SALVATION SCHOOL",
              "OVALE VILLAGE",
              "P.M.G.P.COLONY JOGESHWARI",
              "P.THAKRE CHOWK DADAR",
              "P.THAKRE NAGAR BUS STATION",
              "P.THAKRE NAGAR MARKET",
              "P.THAKRE NAGAR SECTOR - 5",
              "P.THAKRE NAGAR SECTOR-2",
              "P.THAKRE NAGAR SECTOR-8",
              "P.THAKRE UDYAN BUS STATION SEWREE",
              "P.W.D.OFFICE",
              "PADMAJA SOCIETY",
              "PAI NAGAR",
              "PALI HILL - GURU NANAK MARG JUNCTION",
              "PALI MARKET",
              "PALLAVI BUILDING",
              "PANCHAMRUT",
              "PANCHAVATI (GHANSOLI)",
              "PANCHSHEEL APARTMENT",
              "PANDURANG WADI",
              "PANDYA HOSPITAL",
              "PANJARA POL",
              "PANT NAGAR",
              "PANT NAGAR POLICE STATION",
              "PAPER MILL",
              "PARADIGM-B",
              "PARASMANI - MADHUKUNJ SOCIETY",
              "PAREL S.T.DEPOT - SANT ROHIDAS CHOWK",
              "PAREL VILLAGE",
              "PAREL WORKSHOP",
              "PARIJAT BANDRA",
              "PARK STREET",
              "PARLE TILAK SCHOOL",
              "PARLESHWAR MANDIR",
              "PARSHI WADA ANDHERI",
              "PARSI AGYARI",
              "PARSI COLONY JUHU",
              "PARSI COLONY WADALA",
              "PARSI GENERAL HOSPITAL",
              "PARSI PANCHAYAT - DHOBI GHAT",
              "PARSI WADA",
              "PARSIK BANK (NERUL)",
              "PARSIK NAGAR",
              "PARSIK SHIV MANDIR",
              "PARVAT NAGAR",
              "PASCAL WADI",
              "PASSPORT OFFICE",
              "PATHAN WADI",
              "PATIDAR COLONY",
              "PATKAR COLLEGE",
              "PATLI PADA",
              "PATTHAR NAGAR BANDRA",
              "PATWARDHAN SCHOOL - GOVANDI STATION (E)",
              "PAWAR NAGAR BUS STATION",
              "PEER MEHMOOD SHAH BABA DARGAH",
              "PENKAR PADA",
              "PEPSI GARDEN",
              "PERI CROSS ROAD",
              "PERU BAUG",
              "PESTAM SAGAR",
              "PETIT GIRL'S SCHOOL",
              "PETIT HALL",
              "PETROL PUMP - MAHESHWARI MANSION",
              "PETROL PUMP CHANDIVALI",
              "PETROLEUM HOUSE",
              "PHANAS WADI",
              "PHATAK TECHNICAL SCHOOL",
              "PHOENIX CHEMICALS",
              "PHOENIX MILL",
              "PICNIC COTTAGE",
              "PILOT BUNDER",
              "PINK CORNER",
              "PINKY CINEMA",
              "PIONEER HIGH SCHOOL",
              "PIPE LINE",
              "PLAY HOUSE",
              "PLEASANT PARK",
              "PODDAR COLLEGE - RUIA COLLEGE",
              "PODDAR HOSPITAL",
              "POISAR DEPOT",
              "POLICE CAMP WORLI",
              "POLICE COLONY WORLI",
              "POLICE GROUND (GHATKOPAR)",
              "POLICE SUPDT. OFFICE",
              "POLICHEM LTD - PEPSICO",
              "POONAM CHAMBER - SHIVSAGAR ESTATE",
              "POONAM NAGAR",
              "POONAM SAGAR COMPLEX",
              "POST & TELEGRAPHS MULUND",
              "POST OFFICE CHEMBUR",
              "POST OFFICE MATUNGA",
              "POSTAL COLONY",
              "POUSH MATA MANDIR",
              "POWAI CHOWK MULUND",
              "POWAI VIHAR COMPLEX",
              "PRABHADEVI",
              "PRABHU HOTEL (KURAR VILLAGE MRG JUN)",
              "PRAGATI HIGH SCHOOL",
              "PRAPTI SOCIETY",
              "PRARTHANA SAMAJ",
              "PRARTHANALAYA",
              "PRASANNA JEEVAN SOCIETY",
              "PRASANNA SOCIETY",
              "PRATAP NAGAR BHANDUP",
              "PRATAP NAGAR MAJAS",
              "PRATIKSHA NAGAR DEPOT",
              "PRATIKSHA NAGAR NO 1 - SAMAJ MANDIR HALL",
              "PRAVASI INDUSTRIAL COLONY",
              "PREM NAGAR (GOREGAON W)",
              "PREM NAGAR NAPEAN SEA",
              "PREM NAGAR THANE",
              "PREM SAGAR MIRA ROAD",
              "PRESIDENT HOTEL",
              "PRINCESS DOCK",
              "PRINCESS STREET",
              "PRISM TOWER GOREGAON W",
              "PRIYADARSHANI CHUNA BHATTI",
              "PRIYADARSHANI NEPEAN SEA ROAD",
              "PT.PALUSKAR CHOWK",
              "PUMP HOUSE",
              "PUNCH KUTIR",
              "PUNJAB DAIRY",
              "PUNJAB FOUNDRY",
              "PUNJAB WADI",
              "PUSHPA PARK",
              "QUINSCENT HEIGHT",
              "R F NAIK SCHOOL",
              "R.B.I. (FORT)",
              "R.B.I. BKC",
              "R.B.I.COLONY (ANDHERI)",
              "R.B.I.COLONY (BELAPUR)",
              "R.B.I.COLONY (CHEMBUR)",
              "R.B.I.COLONY (DINDOSHI)",
              "R.B.I.COLONY (GOREGAON)",
              "R.B.I.COLONY(BHANDUP VILLAGE-E)",
              "R.C.CHURCH",
              "R.C.F. OFFICE (CHEMBUR)",
              "R.C.F.(CHEMBUR)",
              "R.C.F.COLONY (BHANDUP VILLAGE-E)",
              "R.C.F.COLONY (SHRIKRISHNA SOCIETY)",
              "R.C.F.COLONY - GOLF CLUB",
              "R.C.F.HOSTEL (CHEMBUR)",
              "R.K.STUDIO",
              "R.T.O. - NEW VIKAS HSG SOCIETY ANDHERI",
              "R.T.O.OFFICE - DARGAH WORLI",
              "R.T.O.OFFICE GHATKOPAR",
              "RABALE POLICE STATION",
              "RABALE VILLAGE",
              "RABODI POLICE STATION",
              "RADHA MAHESHWARI CHOWK",
              "RADHA SILK MILL",
              "RAGHUVANSHI MILLS",
              "RAHAT APARTMENT",
              "RAHEJA COLLEGE (S'CRUZ)",
              "RAILWAY ACCIDENT COURT",
              "RAILWAY CROSSING DOCKYARD",
              "RAILWAY HOTEL - CHARNI ROAD JUNCTION",
              "RAILWAY POLICE COLONY (GHATKOPAR)",
              "RAILWAY SANKALP COLONY",
              "RAJ BUCKET FACTORY",
              "RAJ KAPOOR CHOWK - BHABHA HOSPITAL",
              "RAJ KUMAR",
              "RAJ PARK",
              "RAJA SHIVAJI HIGH SCHOOL (HINDU COLONY)",
              "RAJASHREE CINEMA",
              "RAJAWADI HOSPITAL",
              "RAJENDRA NAGAR",
              "RAJHANS SOCIETY BORIVALI",
              "RAJSHIV BUILDING",
              "RALLI WOLF",
              "RAM ASHRAM",
              "RAM BAUG - SHASTRI NAGAR KANDIVALI",
              "RAM BAUG GOREGAON",
              "RAM BHAVAN GHATKOPAR",
              "RAM GANESH GADKARI CHOWK (SHIVAJI PARK)",
              "RAM MANDIR BORIVALI",
              "RAM MANDIR GOREGAON",
              "RAM MANDIR RAILWAY STATION (WEST)",
              "RAM NAGAR BHAYANDAR",
              "RAM NAGAR SHIMPOLI",
              "RAM WADI JOGESHWARI",
              "RAMABAI NAGAR",
              "RAMDA HOTEL (POWAI)",
              "RAMESH HOTEL MALAD",
              "RAMESH NAGAR ANDHERI",
              "RAMESHWAR BANK BORIVALI",
              "RAMESHWAR MANDIR TRUST",
              "RAMGAD (ANITA NAGAR) KANDIVALI",
              "RAMKRISHNA MISSION",
              "RANA & SONS",
              "RANADE ROAD DADAR",
              "RANI LAXMIBAI CHOWK - SION",
              "RANI SATI MARG MUNICIPAL SCHOOL",
              "RANI SATI NAGAR",
              "RASHMI-RATHI SOCIETY",
              "RATODI MADH",
              "RAVIKIRAN SOCIETY MALVANI",
              "RAWAL PADA (BORIVALI - E)",
              "RAWLI CAMP",
              "REAY ROAD BRIDGE",
              "REKHA SADAN - JAIN MANDIR WALKESHWAR",
              "RELIANCE ENERGY (AAREY COLONY)",
              "RELIANCE ENERGY (CHEMBUR)",
              "RELIANCE ENERGY TRAINING CENTRE",
              "RENUKA NAGAR",
              "RETI BUNDER (KHARIGAON)",
              "RETREAT HOTEL AKSA",
              "REYAN INTERNATIONAL SCHOOL",
              "RIDDHI-SIDDHI SOCIETY MULUND",
              "RIZVI COLLEGE BANDRA",
              "RIZVI COMPLEX (CARTER ROAD)",
              "ROBERT GOMES CHOWK BYCULLA",
              "ROYAL COLLEGE",
              "ROYAL COMPLEX",
              "ROYAL HOTEL ( SRUSHTI ) - KASHIMIRA",
              "ROYAL HOTEL JUHU",
              "RTO OFFICE (THANE)",
              "RUBY COMPANY",
              "RUBY SOCIETY CHARKOP",
              "RUIA COLLEGE",
              "RUNWAL PLAZA (THANE)",
              "RUPAREL COLLEGE",
              "RUSHI COMPLEX DAHISAR",
              "RUSHI COMPLEX EXTENSION ( DAHISAR - W )",
              "RUSHI VAN BORIVALI",
              "RUTU PARK (THANE)",
              "RUTU TOWER (BRAHMAND)",
              "S BRIDGE - MANDLIK CHOWK",
              "S. K. RESORT",
              "S.G.BARVE MARG JUNCTION - KURLA",
              "S.K.PATIL AROGYADHAM (MALAD-E)",
              "S.K.PATIL GARDEN CHARNI ROAD",
              "S.K.STONE MIRA ROAD",
              "S.N.D.T. COLLEGE JUHU",
              "S.R.A.CLY. MANKHURD (LALLUBHAI COM)",
              "S.R.A.COLONY (MANKHURD)",
              "S.R.A.COLONY (SOMANI GRAM)",
              "S.R.A.COLONY (WASHI NAKA)",
              "S.T.OFFICE - LOVEGROVE - JARIMARI TEMPLE",
              "S.U.PUMP (YOGI HILL) MULUND",
              "S.V.P VIDYALAY",
              "SADHANA CASTINGS BHANDUP",
              "SAFED POOL",
              "SAHAKAR BAZAR (AIROLI)",
              "SAHAKAR NAGAR (CHEMBUR)",
              "SAHAKAR NAGAR (WADALA)",
              "SAHAKAR TALKIES CHEMBUR",
              "SAHAKARI BHANDAR V'PARLE (W)",
              "SAHAR AIR INDIA HOTEL",
              "SAHAR CARGO COMPLEX",
              "SAHAR P.& T.COLONY NO 1 & ",
              "SAHAR POLICE STATION",
              "SAHARA",
              "SAHYADRI GUEST HOUSE WALKESHWAR",
              "SAHYADRI NAGAR BHANDUP",
              "SAHYADRI NAGAR CHARKOP",
              "SAHYADRI SCHOOL (KALWA)",
              "SAI AMRUT SOCIETY",
              "SAI CHITRA SOCIETY (CHARKOP)",
              "SAI DHAM GRANT ROAD",
              "SAI DHAM MULUND",
              "SAI GARDEN KANDIVALI",
              "SAI SHRADHA SHOPING CENTRE MALVNI",
              "SAIBABA MANDIR (AMRUT NAGAR)",
              "SAIBABA MANDIR (GHATKOPAR)",
              "SAIBABA MANDIR - KOKAN BANK S'NAGAR",
              "SAIBABA MANDIR CHARKOP",
              "SAIBABA MANDIR KANDIVALI",
              "SAIBABA MANDIR MAROL",
              "SAIBABA MANDIR-KOKAN BANK",
              "SAIBABA NAGAR (KANDAR PADA)",
              "SAIBABA NAGAR KANDIVALI",
              "SAIBABA ROAD PAREL",
              "SAIDHAM SOCIETY (NERUL)",
              "SAIKRUPA COMPLEX",
              "SAINATH NAGAR (GHODBUNDER)",
              "SAINATH NAGAR ANDHERI",
              "SAKHAR BHAVAN",
              "SALASAR HANUMAN MANDIR MALAD",
              "SALSAR NAGAR",
              "SALVATION ARMY NAGPADA",
              "SAMAJ MANDIR HALL (SECTOR 10 VASHI)",
              "SAMANA PARIVAR",
              "SAMARTH NAGAR",
              "SAMATA NAGAR (KNDVLI)",
              "SAMATA NAGAR (KOPAR KHRN)",
              "SAMBHAJI NAGAR (KANDIVALI)",
              "SAMBHAJI NAGAR (PARLE)",
              "SAMRAT ASHOK NAGAR",
              "SAMRAT HOTEL",
              "SANDESH HOTEL",
              "SANDHURST STATION ROAD",
              "SANDU WADI",
              "SANGAM NAGAR",
              "SANGHARSH NAGAR (CHANDIVALI)",
              "SANGITA TALKIES",
              "SANJAY GANDHI UDYAN",
              "SANJAY NAGAR JOGESHWARI",
              "SANKALP SOCIETY (NAGARI NIWARA)",
              "SANPADA POLICE CHOWKEY",
              "SANPADA STATION",
              "SANPADA TELE EXCHANGE",
              "SANSKRITI APARTMENTS",
              "SANT GADGE MAHARAJ CHOWK - SAAT RASTA",
              "SANT JAGNADE CHOWK - LALBAUG",
              "SANT MUKTABAI HOSPITAL",
              "SANT RAJINDER SINGH ASHRAM",
              "SANT SAVTA MARKET",
              "SANTACRUZ DEPOT",
              "SANTACRUZ POLICE CHOWKEY BEAT NO.2",
              "SANTACRUZ POLICE STATION",
              "SANTACRUZ STATION ( E )",
              "SANTACRUZ STATION (W)",
              "SANTOSH NAGAR (DINDOSHI)",
              "SANTOSH NAGAR (KANDIVALI-W)",
              "SANTOSH NAGAR EXTENSION",
              "SANTOSHI MATA MANDIR BORIVALI",
              "SANTOSHI MATA MANDIR MULUND",
              "SARAF CHOUDHARI NAGAR",
              "SARASWAT BANK",
              "SARASWATI COMPLEX (DAHISAR)",
              "SARASWATI VIDYA MANDIR",
              "SARDAR CHOWK",
              "SARDAR NAGAR NO 1",
              "SARDAR NAGAR NO 4",
              "SARDAR VALLABHBHAI PATEL COLLEGE",
              "SARIPUT NAGAR",
              "SARSOLE BUS STATION",
              "SARVODAYA HOSPITAL",
              "SARVODAYA MAHABUDDHA VIHAR",
              "SARVODAYA NAGAR BHANDUP",
              "SARVODAYA NAGAR JOGESHWARI",
              "SARVODAYA PARSHWANATH NAGAR MULUND",
              "SASOON DOCK",
              "SATBHAKTI MANDIR",
              "SATHE COLLEGE",
              "SATPUDA SOCIETY",
              "SATYA NAGAR",
              "SATYAM BUILDING",
              "SAURASHTRA BANK",
              "SAVE NAGAR",
              "SAWARPADA",
              "SAWARPADA POST OFFICE",
              "SAYANI MARG",
              "SCLR FLY OVER JUNCTION",
              "SCOUT CAMP",
              "SEAWOOD-DARAVE PHATAK",
              "SEAWOOD-DARAVE RAILWAY STATION",
              "SECTOR 28 & 29 VASHI",
              "SECTOR NO (10-15) VASHI",
              "SECTOR NO 10 AIROLI",
              "SECTOR NO 16 AIROLI",
              "SECTOR NO 17 AIROLI",
              "SECTOR NO 19 (VASHI)",
              "SECTOR NO 26 VASHI",
              "SECTOR NO 4 AIROLI (SAI CLINIC)",
              "SECTOR NO 5 AIROLI",
              "SECTOR NO 6 CHARKOP",
              "SECTOR NO 8 MIRA ROAD",
              "SECTOR NO 9 - JUHU NAGAR MARKET VASHI",
              "SECTOR NO 9 AIROLI",
              "SECTOR-4 AIROLI (CORPORATION BANK)",
              "SEEPZ BUS STATION",
              "SEEPZ VILLAGE",
              "SESSION COURT (GOKULDHAM)",
              "SEVEN BUNGALOWS BUS STATION",
              "SEVEN BUNGALOWS GARDEN",
              "SEWREE COURT",
              "SEWREE NAKA",
              "SEWREE POLICE STATION - DARUKHANA",
              "SEWREE RAILWAY PHATAK",
              "SEWREE STATION (E)",
              "SEWREE STATION (W)",
              "SEWREE STORE",
              "SHAHU NAGAR",
              "SHAKTI HOSPITAL",
              "SHAKTI NAGAR",
              "SHAMRAO VITTHAL BANK (VASHI)",
              "SHANGRILA COMPANY",
              "SHANKAR MANDIR",
              "SHANKAR WADI",
              "SHANKESHWAR BUILDING (GHATKOPAR)",
              "SHANTARAM PATIL CHOWK (VASHI)",
              "SHANTARAM PUJJARE CHOWK",
              "SHANTARAM TALAO",
              "SHANTI ASHRAM",
              "SHANTI ASHRAM JUNCTION",
              "SHANTI BAUG",
              "SHANTI DHAM",
              "SHANTI NAGAR (KALINA)",
              "SHANTI NAGAR GATE MIRA RD",
              "SHANTI NAGAR KANDIVALI",
              "SHANTI NAGAR MAROL",
              "SHANTI NAGAR WADALA",
              "SHANTI SUDHA PARK JAIN MANDIR",
              "SHANTI VAN (BORIVALI)",
              "SHANTI VAN ROAD JUNCTION",
              "SHARDA CINEMA",
              "SHARDASHRAM VIDYAMANDIR",
              "SHASTRI NAGAR (LINK ROAD) GOREGAON",
              "SHASTRI NAGAR (THANE)",
              "SHASTRI NAGAR SCRUZ",
              "SHATABDI HOSPITAL",
              "SHEETAL CINEMA",
              "SHEETAL GARDEN",
              "SHEETAL SAROVAR (MIRA ROAD)",
              "SHEJAL PARK DAHISAR",
              "SHELL COLONY",
              "SHER-E-PUNJAB COLONY",
              "SHERLEY GAOTHAN",
              "SHETHIYA NAGAR",
              "SHETTY VIDYALAYA",
              "SHILP CHOWK (KHARGHAR)",
              "SHIMPOLI NAKA",
              "SHIMPOLI TELEPHONE EXCHANGE",
              "SHIMPOLI VILLAGE",
              "SHINDE WADI",
              "SHIPPING CORPORATION",
              "SHIRAVANE VILLAGE",
              "SHITAL BAUG",
              "SHITALADEVI TEMPLE",
              "SHIV CENTRE",
              "SHIV DARSHAN (TERESA ROAD)",
              "SHIV DHAM (RUSHI COMPLEX)",
              "SHIV PREMI NAGAR",
              "SHIV SHAI PRAKALP MANTRI PARK",
              "SHIV SHAI PRAKALP - MANTRI PARK",
              "SHIV SHRUSTI",
              "SHIVAI VIDYALAYA BHANDUP",
              "SHIVAJI CHOWK (KALWA)",
              "SHIVAJI CHOWK (KHARGHAR)",
              "SHIVAJI CHOWK ANDHERI",
              "SHIVAJI CHOWK MULUND",
              "SHIVAJI CHOWK NERUL",
              "SHIVAJI MAHARAJ VIDYALAYA",
              "SHIVAJI MAIDAN",
              "SHIVAJI NAGAR DAHISAR",
              "SHIVAJI NAGAR DEPOT",
              "SHIVAJI NAGAR JUNCTION",
              "SHIVAJI NAGAR MADH",
              "SHIVAJI NAGAR POST OFFICE",
              "SHIVAJI NAGAR SEWREE",
              "SHIVAJI NAGAR TERMINUS",
              "SHIVAJI NGR.DEPOT",
              "SHIVAJI NGR.JN.",
              "SHIVAJI TALAO",
              "SHIVAJIRAJE COMPLEX (MALAD)",
              "SHIVAJIRAJE COMPLEX EXTESNION (MALAD)",
              "SHIVAR GARDEN",
              "SHIVNER CHOWK - GANESH MANDIR",
              "SHIVNERI BUILDING",
              "SHIVRAJ BHAVAN",
              "SHIVSENA OFFICE (CHEMBUR)",
              "SHOPPERS STOP ANDHERI",
              "SHOPPING PLAZA (CHANDIVALI)",
              "SHRAWAN YESHWANTE CHOWK",
              "SHREE KOTESHWARI MANDIR",
              "SHREE PARLESHWAR SOCIETY",
              "SHREE RAM MILL",
              "SHREE SAI HOSPITAL",
              "SHREE SAIBABA COMPLEX",
              "SHREE SHIVSHANKAR MANDIR",
              "SHREE SWAMI SAMARTH NAGAR",
              "SHREE SWAMI SAMARTH NAGAR EXTENSION",
              "SHREEJI AVENUE SOCIETY",
              "SHREENATH COMPLEX MIRA ROAD",
              "SHREYAS CINEMA",
              "SHRI KRISHNA GARDEN SOCIETY",
              "SHRI KRISHNA INDUSTRIAL ESTATE",
              "SHRI KRISHNA NAGAR (BORIVALI)-SHANTIVAN",
              "SHRIMAD GOKUL",
              "SHRIRANGA SOCIETY",
              "SHUKLAJI STREET",
              "SHYAM NAGAR",
              "SIDDHAPURA IND ESTATE",
              "SIDDHARAJ SOCIETY",
              "SIDDHARTH NAGAR",
              "SIDDHARTHA NAGAR (KANDIVALI)",
              "SIDDHESHWAR - GHARONDA (GHANSOLI)",
              "SIDDHIVINAYAK MANDIR",
              "SIDDHIVINAYAK TOWER",
              "SIDHARTH NAGAR (THANE)",
              "SIKKA NAGAR",
              "SILVER PARK",
              "SIMLA HOUSE",
              "SIMPLEX MILL",
              "SINDHI COLONY",
              "SINDHI SOCIETY GYMKHANA",
              "SIR ALI YAVAR JUNG INSTITUTE",
              "SIR ALI YAVAR JUNG MARG - RANI SATI MARG",
              "SISTERS BUNGALOW",
              "SMALL SCALE INDUSTRIES",
              "SOMAIYA COLLEGE",
              "SOMAIYA COLLEGE (VIDYA VIHAR)",
              "SOMPURI MARKET",
              "SONA INDUSTRIES PREMISES",
              "SONAWALA BUILDING",
              "SONAWALA ROAD - GOREGAON STN EAST",
              "SOUTH-NORTH MARG NO 9",
              "SPECIAL STEEL - RAJENDRA NAGAR",
              "SPRING MILL",
              "SRUSHTI",
              "SRUSHTI POLICE STATION",
              "SSC BOARD OFFICE - ST. LAWRENCE SCHOOL",
              "ST.ANDREW'S CHURCH",
              "ST.ANTHONY CHURCH",
              "ST.JOSEPH TECHNICAL SCHOOL",
              "ST.LAWRENCE HIGH SCHOOL",
              "ST.MARY'S HIGH SCHOOL",
              "ST.PETER'S CHURCH",
              "ST.PIUS SCHOOL KALINA",
              "ST.PIUS SCHOOL MULUND",
              "ST.TERESA CONVENT SCHOOL",
              "ST.THERESA CHURCH",
              "ST.XAVIERS HIGH SCHOOL",
              "ST.XAVIERS HIGH SCHOOL (KASHI VILLAGE)",
              "ST.XAVIERS TECHNICAL INSTITUTE",
              "STANDARD ALKALI COMPANY",
              "STANDARD CHARTERED BANK",
              "STANFORD SOCIETY (THANE)",
              "STATE BANK COLONY DINDOSHI",
              "STATE BANK OF INDIA ANDHERI",
              "STATE BANK OF INDIA BHANDUP",
              "STATE BANK OF INDIA GOREGAON",
              "STATE BANK OF INDIA MALAD",
              "STATE BANK OF INDIA MAROL",
              "STATE BANK OF INDIA PARLE",
              "STRAND CINEMA",
              "SUBHAM PALACE (SECTOR 7)",
              "SUBHASH MARG PARLE",
              "SUBHASH NAGAR (THANE)",
              "SUBHASH NAGAR BANDRA",
              "SUBHASH NAGAR CHEMBUR",
              "SUBHASH NAGAR GHATKOPAR",
              "SUBHASH NAGAR NAHUR",
              "SUBHASH TOWER (KHARIGAON)",
              "SUDAMA NAGAR",
              "SUDHINDRA NAGAR",
              "SUHASINI PAWASKAR MARG",
              "SUKH SAGAR",
              "SUKHMANI HOUSING SOCIETY",
              "SUKUR PARK",
              "SUMAN NAGAR",
              "SUMATI SCHOOL",
              "SUMER HOUSE",
              "SUNDER BAUG (KAMANI)",
              "SUNDER GALLI",
              "SUNDER NAGAR MALAD",
              "SUNDER NAGAR MIRA ROAD",
              "SURYA NAGAR",
              "SURYA NAGAR POLICE CHOWKY",
              "SURYA SHOPPING CENTRE",
              "SUVARNA HOSPITAL",
              "SUVIDHYA SCHOOL",
              "SUYASH SHOPPING CENTRE",
              "SWADESHI MARKET",
              "SWAMI D.SARASWATI CHOWK FORT",
              "SWAMI NARAYAN CHOWK DADAR",
              "SWAMI NARAYAN MANDIR GHATKOPAR",
              "SWAMI VIVEKANAND CHOWK (THANE)",
              "SWAMI VIVEKANAND VIDYALAYA",
              "SWAN MILLS",
              "SWAPNA NAGARI (YOGI HILL)",
              "SWASTIK PARK (BRAHMAND)",
              "SWASTIK REGALIA",
              "SWATI STUDIO",
              "T.B.HOSPITAL",
              "TAD WADI",
              "TAGORE NAGAR JUNCTION",
              "TAGORE NAGAR NO ",
              "TAGORE NAGAR NO ",
              "TAGORE NAGAR NO ",
              "TAGORE NAGAR POST OFFICE",
              "TAGORE NAGAR UDYAN - VIKHROLI BRIDGE",
              "TAKSHILA",
              "TALAVALI NAKA - NOCIL COMPANY",
              "TALOJA PHATAK",
              "TANK BUNDE",
              "TAPESHWAR MANDIR",
              "TAPOVAN ( PATHAN WADI)",
              "TARAPOREWALA AQUARIU",
              "TARDEO BUS STATION - RUSHI MEHTA CHOW",
              "TARUN BHARAT SOCIETY",
              "TATA COLONY ",
              "TATA COLONY BK",
              "TATA COLONY CHUNABHATT",
              "TATA HOSPITAL",
              "TATA MOTORS (THANE)",
              "TATA NAGAR - SAMBHAJI NAGAR",
              "TATA OIL MILL - HINDUSTAN LEVER LTD",
              "TATA POWER CENTRE (MAROL)",
              "TATA POWER HOUSE",
              "TATA POWER STATION",
              "TATA PRESS",
              "TATA UNISYS",
              "TATAPOWER CENTRE (POWAI)",
              "TATVADNYAN VIDYAPITH",
              "TECHNICAL SCHOOL",
              "TECHNO ICB (CHINCHOLI BUNDER RD)",
              "TEEN BAKDA",
              "TEEN BATTI",
              "TEEN TAKI",
              "TELECOM FACTORY",
              "TELEPHONE EXCHANGE BANDRA",
              "TELEPHONE EXCHANGE FOUR B'NGLOW",
              "TELI GULLY",
              "TEMBI PADA",
              "TEMBI PADA NAKA",
              "TEMBI PADA PIPE LINE",
              "TERMINAL BPX",
              "TERNA ENG.COLLEGE(NERUL)",
              "TERNA ENGINEERING COLLEGE",
              "TERNA VIDYALAYA",
              "THAKKAR BAPPA COLONY",
              "THAKUR CINEMA",
              "THAKUR COLLEGE",
              "THAKUR COMPLEX",
              "THAKUR COMPLEX POLICE STATION",
              "THAKUR PAKHADI",
              "THAKUR VILLAGE",
              "THAKURDWAR",
              "THANAWALA LANE",
              "THANE BELAPUR JUNCTION",
              "THANE CIVIL HOSPITAL",
              "THANE STATION (EAST)",
              "TILAK NAGAR STATI",
              "TOBACCO COMPANY",
              "TODDY COMPANY - EMPIRE DYEI",
              "TOLANI COLLEGE",
              "TOLANI NAKA",
              "TOWNSHIP MUNICIPAL SCHOOL MALAD",
              "TRACTOR GATE NO 3 - VASA HOSPIT",
              "TRANSIT CAMP DISPENSA",
              "TRANSPORT CORPORATI",
              "TRIVENI NAG",
              "TRUCK TERMINAL",
              "TULSHET PA",
              "TUMNI PA",
              "TUNGA VILLA",
              "TURBHE NAKA (JANTA MARKET)",
              "TURBHE POLICE STATIC",
              "TWO TANK",
              "UDAYA SHREE MARK",
              "UMA MAHESHWARI MANDIR",
              "UMARSHI BAPPA CHOW",
              "UNICHEM COMPANY",
              "UNIT NO 10 (CENTRAL DAIRY)",
              "UNIT NO 13 (CENTRAL DAIRY)",
              "UNIT NO 2 & ",
              "UNIT NO 6 - AAREY MARKET",
              "UNIT NO 7 (AAREY COLONY)",
              "UNIT NO.3",
              "UNIT NO.8 (AAREY COLONY)",
              "UNIT TRUST OF INDI",
              "UNITY HOUSE",
              "UNNAT NAGAR MUNICIPAL SCHOO",
              "URAN PHAT",
              "URBAN CO.OP.BAN",
              "USHA NAGA",
              "USHMA NAGA",
              "UTC FIRE & SECURITY COMPAN",
              "UTI TRAINING ",
              "UTPAL SANGHAVI SCHOOL",
              "V MALL",
              "V.B.PHADKE CHK - METRO - DHOBI TALAl",
              "V.J.T.I.COLLEGE",
              "VADARPADA (MALAD)",
              "VAIBHAV ASAVARI SOCIETY (WARE HOUSE)",
              "VAIKUNTH DHAM",
              "VAISHALI BHAVAN",
              "VAISHALI NAGAR DAHISAR",
              "VAISHALI NAGAR MULUND",
              "VAKOLA MASJID",
              "VAKOLA PIPE LINES",
              "VAKOLA POLICE STATION",
              "VALLABH PARK",
              "VALNAI COLONY",
              "VANDANA TALKIES - S.T.TERMINUS",
              "VANITA SAMAJ - CHAITYA BHOOMI",
              "VANRAI - MHADA COLONY",
              "VANRAI MHADA - NIRLON INDUSTRIAL ESTATE",
              "VARSHA NAGAR",
              "VARTAK NAGAR (THANE)",
              "VASANT GARDEN (YOGI HILLS)",
              "VASANT VIHAR",
              "VASANT VIHAR TELEPHONE EXCHANGE",
              "VASANTRAO NAIK CHOWK - TARDE",
              "VASANTRAO NAIK CHOWK - TARDEO",
              "VASARI TEKADI NO.2",
              "VASHI (JUHU NAGAR)",
              "VASHI BUS STATION",
              "VASHI RAILWAY STATION",
              "VASHI VILLAGE",
              "VASI NAKA",
              "VASTU ANAND (KHARIGAON)",
              "VATSALABAI DESAI CHOWK",
              "VAZIRA NAKA",
              "VEEJ BHAVAN",
              "VEER HANUMAN NAGAR",
              "VEER KOTWAL UDYAN - DADAR STATION - PLAZA",
              "VEER SAVARKAR CHOWK (NERUL)",
              "VEER SAVARKAR NAGAR (THANE)",
              "VEERA DESAI ROAD",
              "VEERA DESAI ROAD EXT",
              "VENUS BUILDING - WATUMAL ENGG.COLLEGE",
              "VERSOVA BRIDGE",
              "VERSOVA LINK ROAD",
              "VERSOVA VIEW",
              "VESAVE VILLAGE",
              "VESAVE-YARI ROAD BUS STATION",
              "VIDHAN BHAVAN",
              "VIDYA MANDIR",
              "VIDYA NAGARI (NORTH GATE)",
              "VIDYA NAGARI KALINA",
              "VIDYA VIHAR BUS STATION ( W )",
              "VIDYA VIHAR RAILWAY STATION (EAST)",
              "VIDYA VIHAR S.T.",
              "VIDYABEN GARDI SCHOOL",
              "VIHAR LAKE",
              "VIJAY GARDEN",
              "VIJAY NAGAR MAROL",
              "VIJAY NAGAR SOCIETY ANDHERI",
              "VIJAY PRINTING PRESS ANDHERI",
              "VIJAY VALLABH CHOWK - PYDHUNI",
              "VIKAS NAGAR SOCIETY",
              "VIKAS VIDYALAYA",
              "VIKHROLI COURT",
              "VIKHROLI DEPOT",
              "VIKHROLI INDUSTRIAL ESTATE",
              "VIKHROLI PARK SITE",
              "VIKHROLI POLICE STATION",
              "VIKHROLI STATION (E)",
              "VIKHROLI STATION (W)",
              "VIKHROLI VILLAGE (EAST)",
              "VILE PARLE",
              "VILE PARLE POLICE STATION",
              "VILE PARLE RAILWAY CROSSING ( E )",
              "VILE PARLE STATION (E)",
              "VILE PARLE SUB-WAY",
              "VINAS APARTMENT",
              "VINAY HIGH SCHOOL",
              "VINAY INDUSTRY (SUBKUCH MARKET)",
              "VIRWANI ESTATE - SARVODAYA NAGAR",
              "VISHAL HALL - PRAKASH STUDIO",
              "VISHNU NAGAR",
              "VISHWA PRAGATI MANDAL SPORTS COMPLEX",
              "VITHAL BHAI PATEL ROAD JUNCTION",
              "VITTHAL MANDIR (MALAD)",
              "VITTHAL MANDIR - WADALA MARKET",
              "VITTHAL RAKHMAI MANDIR",
              "VIVEK VIDYALAYA",
              "VIVEKANAND COLLEGE",
              "VIVEKANAND HIGH SCHOOL",
              "VIVEKANAND NAGAR (BELAPUR)",
              "VIVEKANAND SCHOOL (SANPADA)",
              "VIVIDH BHARTI",
              "VOICE ROY PARK",
              "VOLTAS THANE",
              "VRINDAVAN SOCIETY",
              "VYAS WADI",
              "WADALA CHURCH",
              "WADALA DEPOT",
              "WADALA DEPOT MONO RAIL STATION",
              "WADALA FLY OVER BRIDGE",
              "WADALA GATE NO 2 - 5",
              "WADALA GATE NO.4",
              "WADALA ROAD MAHUL",
              "WADALA STATION (W)",
              "WADAR PADA MULUND",
              "WADAVLI VILLAGE - BORLA SOCIETY",
              "WADI BUNDER",
              "WADIA HOSPITAL",
              "WAGH BILL",
              "WAGH BILL VILLAGE",
              "WAGHDEVI NAGAR",
              "WAGHESHWARI MANDIR",
              "WAGLE CIRCLE",
              "WAGLE ESTATE POST OFFICE",
              "WAGLE WARD COMMITTEE OFFICE",
              "WALJI LADHA MARG MULUND",
              "WALKESHWAR",
              "WALMIKI NAGAR",
              "WAMANRAO MURANJAN VIDYALAYA",
              "WANKHEDE STADIUM",
              "WARE HOUSE",
              "WESTERN HOTEL - LAXMI BAUG",
              "WESTERN PARK",
              "WHITE HOUSE",
              "WILSON COLLEGE",
              "WOOD HOUSE",
              "WORLD TRADE CENTRE",
              "WORLI DAIRY",
              "WORLI DEPOT",
              "WORLI SEA FACE (N)",
              "WORLI SEA FACE (S)",
              "WORLI VILLAGE",
              "Y.B.CHAVAN MARG JUNCTION",
              "Y.B.CHAVAN PRATISHTAN",
              "YADAV NAGAR",
              "YASHASHRI BUILDING",
              "YASHASVI NAGAR-VARDHAMAN GARDEN",
              "YASHKRIPA BUILDING",
              "YASHO DHAM",
              "YASHODHAN NAGAR (THANE)",
              "YELLOW GATE",
              "YERALA MEDICAL COLLEGE",
              "YOGASHRAM",
              "YOGI HILLS",
              "YOGI HOTEL",
              "YOGI NAGAR",
              "ZAKERIA MASJID",
              "ZARAPKAR STORES",
              "ZULELAL CHOWK GHATKOPAR",
              "ZULELAL CHOWK OSHIWARA",
              "ZUNKA BHAKAR KENDRA (MALVANI)",
              ];
              $( "#startlocation" ).autocomplete({
              source: availableTags
              });
              $( "#destination" ).autocomplete({
              source: availableTags
              });
              } );
    </script>
  </body>
</html>
<!-- <button class="btn" name="subm" type="submit" onclick="price()">Confirm</button><br> -->
<!-- <button class="btn" type="submit">Cancel</button><br>
<button class="btn" type="submit">Payment</button><br>
<button class="btn" type="submit">Download Ticket</button> -->
<!-- <button value="CheckOut" type="submit" class="btn" >Payment</button> -->
